//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.08 at 09:29:27 PM CEST 
//


package edu.anb.core;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ArrowStyleEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ArrowStyleEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ArrowNone"/>
 *     &lt;enumeration value="ArrowOnBoth"/>
 *     &lt;enumeration value="ArrowOnHead"/>
 *     &lt;enumeration value="ArrowOnTail"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ArrowStyleEnum")
@XmlEnum
public enum ArrowStyleEnum {


    /**
     * No arrowhead on either end of the link.
     * 
     */
    @XmlEnumValue("ArrowNone")
    ARROW_NONE("ArrowNone"),

    /**
     * Arrowhead on both ends of the link.
     * 
     */
    @XmlEnumValue("ArrowOnBoth")
    ARROW_ON_BOTH("ArrowOnBoth"),

    /**
     * Arrowhead on End2 of the link.
     * 
     */
    @XmlEnumValue("ArrowOnHead")
    ARROW_ON_HEAD("ArrowOnHead"),

    /**
     * Arrowhead on End1 of the link.
     * 
     */
    @XmlEnumValue("ArrowOnTail")
    ARROW_ON_TAIL("ArrowOnTail");
    private final java.lang.String value;

    ArrowStyleEnum(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static ArrowStyleEnum fromValue(java.lang.String v) {
        for (ArrowStyleEnum c: ArrowStyleEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
