//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.08 at 09:29:27 PM CEST 
//


package edu.anb.core;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{}Font" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="DecimalPlaces" type="{http://www.w3.org/2001/XMLSchema}int" default="2" />
 *       &lt;attribute name="IconFile" type="{http://www.w3.org/2001/XMLSchema}string" default="General" />
 *       &lt;attribute ref="{}Id"/>
 *       &lt;attribute name="IsUser" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="MergeBehaviour" type="{}AttributeBehaviourEnum" />
 *       &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="PasteBehaviour" type="{}AttributeBehaviourEnum" />
 *       &lt;attribute name="Prefix" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SemanticTypeGuid" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="ShowDate" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="ShowIfSet" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="ShowPrefix" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="ShowSeconds" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="ShowSuffix" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="ShowSymbol" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="ShowTime" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="ShowValue" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="Suffix" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Type" use="required" type="{}AttributeTypeEnum" />
 *       &lt;attribute name="UserCanAdd" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="UserCanRemove" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="Visible" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="ShowClassName" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "font"
})
@XmlRootElement(name = "AttributeClass")
public class AttributeClass {

    @XmlElement(name = "Font")
    protected List<Font> font;
    @XmlAttribute(name = "DecimalPlaces")
    protected Integer decimalPlaces;
    @XmlAttribute(name = "IconFile")
    protected java.lang.String iconFile;
    @XmlAttribute(name = "Id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected java.lang.String id;
    @XmlAttribute(name = "IsUser")
    protected Boolean isUser;
    @XmlAttribute(name = "MergeBehaviour")
    protected AttributeBehaviourEnum mergeBehaviour;
    @XmlAttribute(name = "Name", required = true)
    protected java.lang.String name;
    @XmlAttribute(name = "PasteBehaviour")
    protected AttributeBehaviourEnum pasteBehaviour;
    @XmlAttribute(name = "Prefix")
    protected java.lang.String prefix;
    @XmlAttribute(name = "SemanticTypeGuid")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected java.lang.String semanticTypeGuid;
    @XmlAttribute(name = "ShowDate")
    protected Boolean showDate;
    @XmlAttribute(name = "ShowIfSet")
    protected Boolean showIfSet;
    @XmlAttribute(name = "ShowPrefix")
    protected Boolean showPrefix;
    @XmlAttribute(name = "ShowSeconds")
    protected Boolean showSeconds;
    @XmlAttribute(name = "ShowSuffix")
    protected Boolean showSuffix;
    @XmlAttribute(name = "ShowSymbol")
    protected Boolean showSymbol;
    @XmlAttribute(name = "ShowTime")
    protected Boolean showTime;
    @XmlAttribute(name = "ShowValue")
    protected Boolean showValue;
    @XmlAttribute(name = "Suffix")
    protected java.lang.String suffix;
    @XmlAttribute(name = "Type", required = true)
    protected AttributeTypeEnum type;
    @XmlAttribute(name = "UserCanAdd")
    protected Boolean userCanAdd;
    @XmlAttribute(name = "UserCanRemove")
    protected Boolean userCanRemove;
    @XmlAttribute(name = "Visible")
    protected Boolean visible;
    @XmlAttribute(name = "ShowClassName")
    protected Boolean showClassName;

    /**
     * Gets the value of the font property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the font property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFont().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Font }
     * 
     * 
     */
    public List<Font> getFont() {
        if (font == null) {
            font = new ArrayList<Font>();
        }
        return this.font;
    }

    /**
     * Gets the value of the decimalPlaces property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getDecimalPlaces() {
        if (decimalPlaces == null) {
            return  2;
        } else {
            return decimalPlaces;
        }
    }

    /**
     * Sets the value of the decimalPlaces property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDecimalPlaces(Integer value) {
        this.decimalPlaces = value;
    }

    /**
     * Gets the value of the iconFile property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getIconFile() {
        if (iconFile == null) {
            return "General";
        } else {
            return iconFile;
        }
    }

    /**
     * Sets the value of the iconFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setIconFile(java.lang.String value) {
        this.iconFile = value;
    }

    /**
     * Attribute class ID (see IdReferenceLinking).
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setId(java.lang.String value) {
        this.id = value;
    }

    /**
     * Gets the value of the isUser property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIsUser() {
        if (isUser == null) {
            return true;
        } else {
            return isUser;
        }
    }

    /**
     * Sets the value of the isUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsUser(Boolean value) {
        this.isUser = value;
    }

    /**
     * Gets the value of the mergeBehaviour property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeBehaviourEnum }
     *     
     */
    public AttributeBehaviourEnum getMergeBehaviour() {
        return mergeBehaviour;
    }

    /**
     * Sets the value of the mergeBehaviour property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeBehaviourEnum }
     *     
     */
    public void setMergeBehaviour(AttributeBehaviourEnum value) {
        this.mergeBehaviour = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setName(java.lang.String value) {
        this.name = value;
    }

    /**
     * Gets the value of the pasteBehaviour property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeBehaviourEnum }
     *     
     */
    public AttributeBehaviourEnum getPasteBehaviour() {
        return pasteBehaviour;
    }

    /**
     * Sets the value of the pasteBehaviour property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeBehaviourEnum }
     *     
     */
    public void setPasteBehaviour(AttributeBehaviourEnum value) {
        this.pasteBehaviour = value;
    }

    /**
     * Gets the value of the prefix property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getPrefix() {
        return prefix;
    }

    /**
     * Sets the value of the prefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setPrefix(java.lang.String value) {
        this.prefix = value;
    }

    /**
     * Gets the value of the semanticTypeGuid property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getSemanticTypeGuid() {
        return semanticTypeGuid;
    }

    /**
     * Sets the value of the semanticTypeGuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setSemanticTypeGuid(java.lang.String value) {
        this.semanticTypeGuid = value;
    }

    /**
     * Gets the value of the showDate property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isShowDate() {
        if (showDate == null) {
            return true;
        } else {
            return showDate;
        }
    }

    /**
     * Sets the value of the showDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowDate(Boolean value) {
        this.showDate = value;
    }

    /**
     * Gets the value of the showIfSet property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isShowIfSet() {
        if (showIfSet == null) {
            return false;
        } else {
            return showIfSet;
        }
    }

    /**
     * Sets the value of the showIfSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowIfSet(Boolean value) {
        this.showIfSet = value;
    }

    /**
     * Gets the value of the showPrefix property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isShowPrefix() {
        if (showPrefix == null) {
            return false;
        } else {
            return showPrefix;
        }
    }

    /**
     * Sets the value of the showPrefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowPrefix(Boolean value) {
        this.showPrefix = value;
    }

    /**
     * Gets the value of the showSeconds property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isShowSeconds() {
        if (showSeconds == null) {
            return false;
        } else {
            return showSeconds;
        }
    }

    /**
     * Sets the value of the showSeconds property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowSeconds(Boolean value) {
        this.showSeconds = value;
    }

    /**
     * Gets the value of the showSuffix property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isShowSuffix() {
        if (showSuffix == null) {
            return false;
        } else {
            return showSuffix;
        }
    }

    /**
     * Sets the value of the showSuffix property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowSuffix(Boolean value) {
        this.showSuffix = value;
    }

    /**
     * Gets the value of the showSymbol property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isShowSymbol() {
        if (showSymbol == null) {
            return true;
        } else {
            return showSymbol;
        }
    }

    /**
     * Sets the value of the showSymbol property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowSymbol(Boolean value) {
        this.showSymbol = value;
    }

    /**
     * Gets the value of the showTime property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isShowTime() {
        if (showTime == null) {
            return true;
        } else {
            return showTime;
        }
    }

    /**
     * Sets the value of the showTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowTime(Boolean value) {
        this.showTime = value;
    }

    /**
     * Gets the value of the showValue property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isShowValue() {
        if (showValue == null) {
            return true;
        } else {
            return showValue;
        }
    }

    /**
     * Sets the value of the showValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowValue(Boolean value) {
        this.showValue = value;
    }

    /**
     * Gets the value of the suffix property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getSuffix() {
        return suffix;
    }

    /**
     * Sets the value of the suffix property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setSuffix(java.lang.String value) {
        this.suffix = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeTypeEnum }
     *     
     */
    public AttributeTypeEnum getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeTypeEnum }
     *     
     */
    public void setType(AttributeTypeEnum value) {
        this.type = value;
    }

    /**
     * Gets the value of the userCanAdd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isUserCanAdd() {
        if (userCanAdd == null) {
            return true;
        } else {
            return userCanAdd;
        }
    }

    /**
     * Sets the value of the userCanAdd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUserCanAdd(Boolean value) {
        this.userCanAdd = value;
    }

    /**
     * Gets the value of the userCanRemove property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isUserCanRemove() {
        if (userCanRemove == null) {
            return true;
        } else {
            return userCanRemove;
        }
    }

    /**
     * Sets the value of the userCanRemove property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUserCanRemove(Boolean value) {
        this.userCanRemove = value;
    }

    /**
     * Gets the value of the visible property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isVisible() {
        if (visible == null) {
            return true;
        } else {
            return visible;
        }
    }

    /**
     * Sets the value of the visible property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVisible(Boolean value) {
        this.visible = value;
    }

    /**
     * Gets the value of the showClassName property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isShowClassName() {
        return showClassName;
    }

    /**
     * Sets the value of the showClassName property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowClassName(Boolean value) {
        this.showClassName = value;
    }

}
