//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.08 at 09:29:27 PM CEST 
//


package edu.anb.core;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AutoSizeOptionEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AutoSizeOptionEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Autosize"/>
 *     &lt;enumeration value="AutosizeManual"/>
 *     &lt;enumeration value="AutosizeManualHeight"/>
 *     &lt;enumeration value="AutosizeManualWidth"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AutoSizeOptionEnum")
@XmlEnum
public enum AutoSizeOptionEnum {


    /**
     * The width and height are auto sized to optimize the text fit. Cannot manually set the width or the height.
     * 
     */
    @XmlEnumValue("Autosize")
    AUTOSIZE("Autosize"),

    /**
     * The height and width are constant values.
     * 
     */
    @XmlEnumValue("AutosizeManual")
    AUTOSIZE_MANUAL("AutosizeManual"),

    /**
     * The height is a constant value. The width is auto sized to optimize the text fit. Cannot manually set the width.
     * 
     */
    @XmlEnumValue("AutosizeManualHeight")
    AUTOSIZE_MANUAL_HEIGHT("AutosizeManualHeight"),

    /**
     * The width is a constant value. The height is auto sized to optimize the text fit. Cannot manually set the height.
     * 
     */
    @XmlEnumValue("AutosizeManualWidth")
    AUTOSIZE_MANUAL_WIDTH("AutosizeManualWidth");
    private final java.lang.String value;

    AutoSizeOptionEnum(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static AutoSizeOptionEnum fromValue(java.lang.String v) {
        for (AutoSizeOptionEnum c: AutoSizeOptionEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
