//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.08 at 09:29:27 PM CEST 
//


package edu.anb.core;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}BoxStyle" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Depth" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *       &lt;attribute name="Height" type="{http://www.w3.org/2001/XMLSchema}int" default="100" />
 *       &lt;attribute name="TextX" type="{http://www.w3.org/2001/XMLSchema}int" default="2" />
 *       &lt;attribute name="TextY" type="{http://www.w3.org/2001/XMLSchema}int" default="1" />
 *       &lt;attribute name="Width" type="{http://www.w3.org/2001/XMLSchema}int" default="100" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "boxStyle"
})
@XmlRootElement(name = "Box")
public class Box {

    @XmlElement(name = "BoxStyle")
    protected BoxStyle boxStyle;
    @XmlAttribute(name = "Depth")
    protected Integer depth;
    @XmlAttribute(name = "Height")
    protected Integer height;
    @XmlAttribute(name = "TextX")
    protected Integer textX;
    @XmlAttribute(name = "TextY")
    protected Integer textY;
    @XmlAttribute(name = "Width")
    protected Integer width;

    /**
     * Gets the value of the boxStyle property.
     * 
     * @return
     *     possible object is
     *     {@link BoxStyle }
     *     
     */
    public BoxStyle getBoxStyle() {
        return boxStyle;
    }

    /**
     * Sets the value of the boxStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link BoxStyle }
     *     
     */
    public void setBoxStyle(BoxStyle value) {
        this.boxStyle = value;
    }

    /**
     * Gets the value of the depth property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getDepth() {
        if (depth == null) {
            return  0;
        } else {
            return depth;
        }
    }

    /**
     * Sets the value of the depth property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDepth(Integer value) {
        this.depth = value;
    }

    /**
     * Gets the value of the height property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getHeight() {
        if (height == null) {
            return  100;
        } else {
            return height;
        }
    }

    /**
     * Sets the value of the height property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setHeight(Integer value) {
        this.height = value;
    }

    /**
     * Gets the value of the textX property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getTextX() {
        if (textX == null) {
            return  2;
        } else {
            return textX;
        }
    }

    /**
     * Sets the value of the textX property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTextX(Integer value) {
        this.textX = value;
    }

    /**
     * Gets the value of the textY property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getTextY() {
        if (textY == null) {
            return  1;
        } else {
            return textY;
        }
    }

    /**
     * Sets the value of the textY property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTextY(Integer value) {
        this.textY = value;
    }

    /**
     * Gets the value of the width property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getWidth() {
        if (width == null) {
            return  100;
        } else {
            return width;
        }
    }

    /**
     * Sets the value of the width property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setWidth(Integer value) {
        this.width = value;
    }

}
