//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.08 at 09:29:27 PM CEST 
//


package edu.anb.core;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}TimeZone" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="DateSet" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="DateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="DateTimeDescription" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="GradeOneIndex" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *       &lt;attribute ref="{}GradeOneReference"/>
 *       &lt;attribute name="GradeThreeIndex" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *       &lt;attribute ref="{}GradeThreeReference"/>
 *       &lt;attribute name="GradeTwoIndex" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *       &lt;attribute ref="{}GradeTwoReference"/>
 *       &lt;attribute name="LocalDateTimeOffset" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="SourceReference" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SourceType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Summary" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Text" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="TimeSet" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "timeZone"
})
@XmlRootElement(name = "Card")
public class Card {

    @XmlElement(name = "TimeZone")
    protected TimeZone timeZone;
    @XmlAttribute(name = "DateSet")
    protected Boolean dateSet;
    @XmlAttribute(name = "DateTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateTime;
    @XmlAttribute(name = "DateTimeDescription")
    protected java.lang.String dateTimeDescription;
    @XmlAttribute(name = "GradeOneIndex")
    protected Integer gradeOneIndex;
    @XmlAttribute(name = "GradeOneReference")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object gradeOneReference;
    @XmlAttribute(name = "GradeThreeIndex")
    protected Integer gradeThreeIndex;
    @XmlAttribute(name = "GradeThreeReference")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object gradeThreeReference;
    @XmlAttribute(name = "GradeTwoIndex")
    protected Integer gradeTwoIndex;
    @XmlAttribute(name = "GradeTwoReference")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object gradeTwoReference;
    @XmlAttribute(name = "LocalDateTimeOffset")
    protected BigInteger localDateTimeOffset;
    @XmlAttribute(name = "SourceReference")
    protected java.lang.String sourceReference;
    @XmlAttribute(name = "SourceType")
    protected java.lang.String sourceType;
    @XmlAttribute(name = "Summary")
    protected java.lang.String summary;
    @XmlAttribute(name = "Text")
    protected java.lang.String text;
    @XmlAttribute(name = "TimeSet")
    protected Boolean timeSet;

    /**
     * Gets the value of the timeZone property.
     * 
     * @return
     *     possible object is
     *     {@link TimeZone }
     *     
     */
    public TimeZone getTimeZone() {
        return timeZone;
    }

    /**
     * Sets the value of the timeZone property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeZone }
     *     
     */
    public void setTimeZone(TimeZone value) {
        this.timeZone = value;
    }

    /**
     * Gets the value of the dateSet property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isDateSet() {
        if (dateSet == null) {
            return false;
        } else {
            return dateSet;
        }
    }

    /**
     * Sets the value of the dateSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDateSet(Boolean value) {
        this.dateSet = value;
    }

    /**
     * Gets the value of the dateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateTime() {
        return dateTime;
    }

    /**
     * Sets the value of the dateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateTime(XMLGregorianCalendar value) {
        this.dateTime = value;
    }

    /**
     * Gets the value of the dateTimeDescription property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getDateTimeDescription() {
        return dateTimeDescription;
    }

    /**
     * Sets the value of the dateTimeDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setDateTimeDescription(java.lang.String value) {
        this.dateTimeDescription = value;
    }

    /**
     * Gets the value of the gradeOneIndex property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getGradeOneIndex() {
        if (gradeOneIndex == null) {
            return  0;
        } else {
            return gradeOneIndex;
        }
    }

    /**
     * Sets the value of the gradeOneIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setGradeOneIndex(Integer value) {
        this.gradeOneIndex = value;
    }

    /**
     * IDREF for the card's grade one in the chart's grading system.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getGradeOneReference() {
        return gradeOneReference;
    }

    /**
     * Sets the value of the gradeOneReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setGradeOneReference(Object value) {
        this.gradeOneReference = value;
    }

    /**
     * Gets the value of the gradeThreeIndex property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getGradeThreeIndex() {
        if (gradeThreeIndex == null) {
            return  0;
        } else {
            return gradeThreeIndex;
        }
    }

    /**
     * Sets the value of the gradeThreeIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setGradeThreeIndex(Integer value) {
        this.gradeThreeIndex = value;
    }

    /**
     * IDREF for the card's grade three in the chart's grading system.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getGradeThreeReference() {
        return gradeThreeReference;
    }

    /**
     * Sets the value of the gradeThreeReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setGradeThreeReference(Object value) {
        this.gradeThreeReference = value;
    }

    /**
     * Gets the value of the gradeTwoIndex property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getGradeTwoIndex() {
        if (gradeTwoIndex == null) {
            return  0;
        } else {
            return gradeTwoIndex;
        }
    }

    /**
     * Sets the value of the gradeTwoIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setGradeTwoIndex(Integer value) {
        this.gradeTwoIndex = value;
    }

    /**
     * IDREF for the card's grade two in the chart's grading system.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getGradeTwoReference() {
        return gradeTwoReference;
    }

    /**
     * Sets the value of the gradeTwoReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setGradeTwoReference(Object value) {
        this.gradeTwoReference = value;
    }

    /**
     * Gets the value of the localDateTimeOffset property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLocalDateTimeOffset() {
        return localDateTimeOffset;
    }

    /**
     * Sets the value of the localDateTimeOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLocalDateTimeOffset(BigInteger value) {
        this.localDateTimeOffset = value;
    }

    /**
     * Gets the value of the sourceReference property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getSourceReference() {
        return sourceReference;
    }

    /**
     * Sets the value of the sourceReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setSourceReference(java.lang.String value) {
        this.sourceReference = value;
    }

    /**
     * Gets the value of the sourceType property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getSourceType() {
        return sourceType;
    }

    /**
     * Sets the value of the sourceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setSourceType(java.lang.String value) {
        this.sourceType = value;
    }

    /**
     * Gets the value of the summary property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getSummary() {
        return summary;
    }

    /**
     * Sets the value of the summary property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setSummary(java.lang.String value) {
        this.summary = value;
    }

    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setText(java.lang.String value) {
        this.text = value;
    }

    /**
     * Gets the value of the timeSet property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isTimeSet() {
        if (timeSet == null) {
            return false;
        } else {
            return timeSet;
        }
    }

    /**
     * Sets the value of the timeSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTimeSet(Boolean value) {
        this.timeSet = value;
    }

}
