//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.08 at 09:29:27 PM CEST 
//


package edu.anb.core;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{}ApplicationVersion" minOccurs="0"/>
 *         &lt;element ref="{http://www.i2group.com/Schemas/2001-12-07/LCXSchema}LibraryCatalogue" minOccurs="0"/>
 *         &lt;element ref="{}PropertyBagCollection" minOccurs="0"/>
 *         &lt;element ref="{}CustomImageCollection" minOccurs="0"/>
 *         &lt;element ref="{}GradeOne" minOccurs="0"/>
 *         &lt;element ref="{}GradeTwo" minOccurs="0"/>
 *         &lt;element ref="{}GradeThree" minOccurs="0"/>
 *         &lt;element ref="{}SourceHints" minOccurs="0"/>
 *         &lt;element ref="{}StrengthCollection" minOccurs="0"/>
 *         &lt;element ref="{}AttributeClassCollection" minOccurs="0"/>
 *         &lt;element ref="{}EntityTypeCollection" minOccurs="0"/>
 *         &lt;element ref="{}LinkTypeCollection" minOccurs="0"/>
 *         &lt;element ref="{}Font" minOccurs="0"/>
 *         &lt;element ref="{}DatabaseProxyCollection" minOccurs="0"/>
 *         &lt;element ref="{}DateTimeFormatCollection" minOccurs="0"/>
 *         &lt;element ref="{}CurrentStyleCollection" minOccurs="0"/>
 *         &lt;element ref="{}TimeZone" minOccurs="0"/>
 *         &lt;element ref="{}TimeBar" minOccurs="0"/>
 *         &lt;element ref="{}PrintSettings" minOccurs="0"/>
 *         &lt;element ref="{}Summary" minOccurs="0"/>
 *         &lt;element ref="{}ChartItemCollection" minOccurs="0"/>
 *         &lt;element ref="{}ConnectionCollection" minOccurs="0"/>
 *         &lt;element ref="{}JunctionCollection" minOccurs="0"/>
 *         &lt;element ref="{}GroupCollection" minOccurs="0"/>
 *         &lt;element ref="{}PaletteCollection" minOccurs="0"/>
 *         &lt;element ref="{}PaletteBarCollection" minOccurs="0"/>
 *         &lt;element ref="{}LegendDefinition" minOccurs="0"/>
 *         &lt;element ref="{}SnapshotCollection" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="SchemaVersion" type="{http://www.w3.org/2001/XMLSchema}string" default="7.0.0.1" />
 *       &lt;attribute name="MsxmlVersion" type="{http://www.w3.org/2001/XMLSchema}string" default="4.20.9818.0" />
 *       &lt;attribute name="BackColour" type="{http://www.w3.org/2001/XMLSchema}int" default="16777215" />
 *       &lt;attribute name="BlankLinkLabels" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="DefaultDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="DefaultDateTimeForNewChart" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="DefaultLinkSpacing" type="{http://www.w3.org/2001/XMLSchema}double" default="0.295275590551181" />
 *       &lt;attribute name="DefaultTickRate" type="{http://www.w3.org/2001/XMLSchema}double" default="1" />
 *       &lt;attribute name="GridHeightSize" type="{http://www.w3.org/2001/XMLSchema}double" default="0.295275590551181" />
 *       &lt;attribute name="GridVisibleOnAllViews" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="GridWidthSize" type="{http://www.w3.org/2001/XMLSchema}double" default="0.295275590551181" />
 *       &lt;attribute name="HideMatchingTimeZoneFormat" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="IdReferenceLinking" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="IsBackColourFilled" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="LabelRule" type="{}LabelMergeAndPasteRuleEnum" default="LabelRuleMerge" />
 *       &lt;attribute name="LabelSumNumericLinks" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="Rigorous" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="ShowAllFlag" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="HiddenItemsVisibility" type="{}HiddenItemsVisibilityEnum" default="ItemsVisibilityHidden" />
 *       &lt;attribute name="ShowPages" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="SnapToGrid" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="TimeBarVisible" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="TypeIconDrawingMode" type="{}TypeIconDrawingModeEnum" default="HighQuality" />
 *       &lt;attribute name="UseDefaultLinkSpacingWhenDragging" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="UseLocalTimeZone" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="UseWiringHeightForThemeIcon" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="WiringDistanceFar" type="{http://www.w3.org/2001/XMLSchema}double" default="0.393700787401575" />
 *       &lt;attribute name="WiringDistanceNear" type="{http://www.w3.org/2001/XMLSchema}double" default="0.078740157480315" />
 *       &lt;attribute name="WiringHeight" type="{http://www.w3.org/2001/XMLSchema}double" default="0.196850393700787" />
 *       &lt;attribute name="WiringSpacing" type="{http://www.w3.org/2001/XMLSchema}double" default="0.196850393700787" />
 *       &lt;attribute name="CoverSheetShowOnOpen" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "applicationVersionAndLibraryCatalogueAndPropertyBagCollection"
})
@XmlRootElement(name = "Chart")
public class Chart {

    @XmlElements({
        @XmlElement(name = "ApplicationVersion", type = ApplicationVersion.class),
        @XmlElement(name = "LibraryCatalogue", namespace = "http://www.i2group.com/Schemas/2001-12-07/LCXSchema", type = LibraryCatalogueType.class),
        @XmlElement(name = "PropertyBagCollection", type = PropertyBagCollection.class),
        @XmlElement(name = "CustomImageCollection", type = CustomImageCollection.class),
        @XmlElement(name = "GradeOne", type = GradeOne.class),
        @XmlElement(name = "GradeTwo", type = GradeTwo.class),
        @XmlElement(name = "GradeThree", type = GradeThree.class),
        @XmlElement(name = "SourceHints", type = SourceHints.class),
        @XmlElement(name = "StrengthCollection", type = StrengthCollection.class),
        @XmlElement(name = "AttributeClassCollection", type = AttributeClassCollection.class),
        @XmlElement(name = "EntityTypeCollection", type = EntityTypeCollection.class),
        @XmlElement(name = "LinkTypeCollection", type = LinkTypeCollection.class),
        @XmlElement(name = "Font", type = Font.class),
        @XmlElement(name = "DatabaseProxyCollection", type = DatabaseProxyCollection.class),
        @XmlElement(name = "DateTimeFormatCollection", type = DateTimeFormatCollection.class),
        @XmlElement(name = "CurrentStyleCollection", type = CurrentStyleCollection.class),
        @XmlElement(name = "TimeZone", type = TimeZone.class),
        @XmlElement(name = "TimeBar", type = TimeBar.class),
        @XmlElement(name = "PrintSettings", type = PrintSettings.class),
        @XmlElement(name = "Summary", type = Summary.class),
        @XmlElement(name = "ChartItemCollection", type = ChartItemCollection.class),
        @XmlElement(name = "ConnectionCollection", type = ConnectionCollection.class),
        @XmlElement(name = "JunctionCollection", type = JunctionCollection.class),
        @XmlElement(name = "GroupCollection", type = GroupCollection.class),
        @XmlElement(name = "PaletteCollection", type = PaletteCollection.class),
        @XmlElement(name = "PaletteBarCollection", type = PaletteBarCollection.class),
        @XmlElement(name = "LegendDefinition", type = LegendDefinition.class),
        @XmlElement(name = "SnapshotCollection", type = SnapshotCollection.class)
    })
    protected List<Object> applicationVersionAndLibraryCatalogueAndPropertyBagCollection;
    @XmlAttribute(name = "SchemaVersion")
    protected java.lang.String schemaVersion;
    @XmlAttribute(name = "MsxmlVersion")
    protected java.lang.String msxmlVersion;
    @XmlAttribute(name = "BackColour")
    protected Integer backColour;
    @XmlAttribute(name = "BlankLinkLabels")
    protected Boolean blankLinkLabels;
    @XmlAttribute(name = "DefaultDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar defaultDate;
    @XmlAttribute(name = "DefaultDateTimeForNewChart")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar defaultDateTimeForNewChart;
    @XmlAttribute(name = "DefaultLinkSpacing")
    protected Double defaultLinkSpacing;
    @XmlAttribute(name = "DefaultTickRate")
    protected Double defaultTickRate;
    @XmlAttribute(name = "GridHeightSize")
    protected Double gridHeightSize;
    @XmlAttribute(name = "GridVisibleOnAllViews")
    protected Boolean gridVisibleOnAllViews;
    @XmlAttribute(name = "GridWidthSize")
    protected Double gridWidthSize;
    @XmlAttribute(name = "HideMatchingTimeZoneFormat")
    protected Boolean hideMatchingTimeZoneFormat;
    @XmlAttribute(name = "IdReferenceLinking")
    protected Boolean idReferenceLinking;
    @XmlAttribute(name = "IsBackColourFilled")
    protected Boolean isBackColourFilled;
    @XmlAttribute(name = "LabelRule")
    protected LabelMergeAndPasteRuleEnum labelRule;
    @XmlAttribute(name = "LabelSumNumericLinks")
    protected Boolean labelSumNumericLinks;
    @XmlAttribute(name = "Rigorous")
    protected Boolean rigorous;
    @XmlAttribute(name = "ShowAllFlag")
    protected Boolean showAllFlag;
    @XmlAttribute(name = "HiddenItemsVisibility")
    protected HiddenItemsVisibilityEnum hiddenItemsVisibility;
    @XmlAttribute(name = "ShowPages")
    protected Boolean showPages;
    @XmlAttribute(name = "SnapToGrid")
    protected Boolean snapToGrid;
    @XmlAttribute(name = "TimeBarVisible")
    protected Boolean timeBarVisible;
    @XmlAttribute(name = "TypeIconDrawingMode")
    protected TypeIconDrawingModeEnum typeIconDrawingMode;
    @XmlAttribute(name = "UseDefaultLinkSpacingWhenDragging")
    protected Boolean useDefaultLinkSpacingWhenDragging;
    @XmlAttribute(name = "UseLocalTimeZone")
    protected Boolean useLocalTimeZone;
    @XmlAttribute(name = "UseWiringHeightForThemeIcon")
    protected Boolean useWiringHeightForThemeIcon;
    @XmlAttribute(name = "WiringDistanceFar")
    protected Double wiringDistanceFar;
    @XmlAttribute(name = "WiringDistanceNear")
    protected Double wiringDistanceNear;
    @XmlAttribute(name = "WiringHeight")
    protected Double wiringHeight;
    @XmlAttribute(name = "WiringSpacing")
    protected Double wiringSpacing;
    @XmlAttribute(name = "CoverSheetShowOnOpen")
    protected Boolean coverSheetShowOnOpen;

    /**
     * Gets the value of the applicationVersionAndLibraryCatalogueAndPropertyBagCollection property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the applicationVersionAndLibraryCatalogueAndPropertyBagCollection property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getApplicationVersionAndLibraryCatalogueAndPropertyBagCollection().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ApplicationVersion }
     * {@link LibraryCatalogueType }
     * {@link PropertyBagCollection }
     * {@link CustomImageCollection }
     * {@link GradeOne }
     * {@link GradeTwo }
     * {@link GradeThree }
     * {@link SourceHints }
     * {@link StrengthCollection }
     * {@link AttributeClassCollection }
     * {@link EntityTypeCollection }
     * {@link LinkTypeCollection }
     * {@link Font }
     * {@link DatabaseProxyCollection }
     * {@link DateTimeFormatCollection }
     * {@link CurrentStyleCollection }
     * {@link TimeZone }
     * {@link TimeBar }
     * {@link PrintSettings }
     * {@link Summary }
     * {@link ChartItemCollection }
     * {@link ConnectionCollection }
     * {@link JunctionCollection }
     * {@link GroupCollection }
     * {@link PaletteCollection }
     * {@link PaletteBarCollection }
     * {@link LegendDefinition }
     * {@link SnapshotCollection }
     * 
     * 
     */
    public List<Object> getApplicationVersionAndLibraryCatalogueAndPropertyBagCollection() {
        if (applicationVersionAndLibraryCatalogueAndPropertyBagCollection == null) {
            applicationVersionAndLibraryCatalogueAndPropertyBagCollection = new ArrayList<Object>();
        }
        return this.applicationVersionAndLibraryCatalogueAndPropertyBagCollection;
    }

    /**
     * Gets the value of the schemaVersion property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getSchemaVersion() {
        if (schemaVersion == null) {
            return "7.0.0.1";
        } else {
            return schemaVersion;
        }
    }

    /**
     * Sets the value of the schemaVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setSchemaVersion(java.lang.String value) {
        this.schemaVersion = value;
    }

    /**
     * Gets the value of the msxmlVersion property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getMsxmlVersion() {
        if (msxmlVersion == null) {
            return "4.20.9818.0";
        } else {
            return msxmlVersion;
        }
    }

    /**
     * Sets the value of the msxmlVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setMsxmlVersion(java.lang.String value) {
        this.msxmlVersion = value;
    }

    /**
     * Gets the value of the backColour property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getBackColour() {
        if (backColour == null) {
            return  16777215;
        } else {
            return backColour;
        }
    }

    /**
     * Sets the value of the backColour property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBackColour(Integer value) {
        this.backColour = value;
    }

    /**
     * Gets the value of the blankLinkLabels property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isBlankLinkLabels() {
        if (blankLinkLabels == null) {
            return false;
        } else {
            return blankLinkLabels;
        }
    }

    /**
     * Sets the value of the blankLinkLabels property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBlankLinkLabels(Boolean value) {
        this.blankLinkLabels = value;
    }

    /**
     * Gets the value of the defaultDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDefaultDate() {
        return defaultDate;
    }

    /**
     * Sets the value of the defaultDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDefaultDate(XMLGregorianCalendar value) {
        this.defaultDate = value;
    }

    /**
     * Gets the value of the defaultDateTimeForNewChart property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDefaultDateTimeForNewChart() {
        return defaultDateTimeForNewChart;
    }

    /**
     * Sets the value of the defaultDateTimeForNewChart property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDefaultDateTimeForNewChart(XMLGregorianCalendar value) {
        this.defaultDateTimeForNewChart = value;
    }

    /**
     * Gets the value of the defaultLinkSpacing property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public double getDefaultLinkSpacing() {
        if (defaultLinkSpacing == null) {
            return  0.295275590551181D;
        } else {
            return defaultLinkSpacing;
        }
    }

    /**
     * Sets the value of the defaultLinkSpacing property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setDefaultLinkSpacing(Double value) {
        this.defaultLinkSpacing = value;
    }

    /**
     * Gets the value of the defaultTickRate property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public double getDefaultTickRate() {
        if (defaultTickRate == null) {
            return  1.0D;
        } else {
            return defaultTickRate;
        }
    }

    /**
     * Sets the value of the defaultTickRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setDefaultTickRate(Double value) {
        this.defaultTickRate = value;
    }

    /**
     * Gets the value of the gridHeightSize property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public double getGridHeightSize() {
        if (gridHeightSize == null) {
            return  0.295275590551181D;
        } else {
            return gridHeightSize;
        }
    }

    /**
     * Sets the value of the gridHeightSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setGridHeightSize(Double value) {
        this.gridHeightSize = value;
    }

    /**
     * Gets the value of the gridVisibleOnAllViews property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isGridVisibleOnAllViews() {
        if (gridVisibleOnAllViews == null) {
            return true;
        } else {
            return gridVisibleOnAllViews;
        }
    }

    /**
     * Sets the value of the gridVisibleOnAllViews property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setGridVisibleOnAllViews(Boolean value) {
        this.gridVisibleOnAllViews = value;
    }

    /**
     * Gets the value of the gridWidthSize property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public double getGridWidthSize() {
        if (gridWidthSize == null) {
            return  0.295275590551181D;
        } else {
            return gridWidthSize;
        }
    }

    /**
     * Sets the value of the gridWidthSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setGridWidthSize(Double value) {
        this.gridWidthSize = value;
    }

    /**
     * Gets the value of the hideMatchingTimeZoneFormat property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isHideMatchingTimeZoneFormat() {
        if (hideMatchingTimeZoneFormat == null) {
            return false;
        } else {
            return hideMatchingTimeZoneFormat;
        }
    }

    /**
     * Sets the value of the hideMatchingTimeZoneFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHideMatchingTimeZoneFormat(Boolean value) {
        this.hideMatchingTimeZoneFormat = value;
    }

    /**
     * Gets the value of the idReferenceLinking property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIdReferenceLinking() {
        if (idReferenceLinking == null) {
            return true;
        } else {
            return idReferenceLinking;
        }
    }

    /**
     * Sets the value of the idReferenceLinking property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIdReferenceLinking(Boolean value) {
        this.idReferenceLinking = value;
    }

    /**
     * Gets the value of the isBackColourFilled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIsBackColourFilled() {
        if (isBackColourFilled == null) {
            return true;
        } else {
            return isBackColourFilled;
        }
    }

    /**
     * Sets the value of the isBackColourFilled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsBackColourFilled(Boolean value) {
        this.isBackColourFilled = value;
    }

    /**
     * Gets the value of the labelRule property.
     * 
     * @return
     *     possible object is
     *     {@link LabelMergeAndPasteRuleEnum }
     *     
     */
    public LabelMergeAndPasteRuleEnum getLabelRule() {
        if (labelRule == null) {
            return LabelMergeAndPasteRuleEnum.LABEL_RULE_MERGE;
        } else {
            return labelRule;
        }
    }

    /**
     * Sets the value of the labelRule property.
     * 
     * @param value
     *     allowed object is
     *     {@link LabelMergeAndPasteRuleEnum }
     *     
     */
    public void setLabelRule(LabelMergeAndPasteRuleEnum value) {
        this.labelRule = value;
    }

    /**
     * Gets the value of the labelSumNumericLinks property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isLabelSumNumericLinks() {
        if (labelSumNumericLinks == null) {
            return false;
        } else {
            return labelSumNumericLinks;
        }
    }

    /**
     * Sets the value of the labelSumNumericLinks property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLabelSumNumericLinks(Boolean value) {
        this.labelSumNumericLinks = value;
    }

    /**
     * Gets the value of the rigorous property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isRigorous() {
        if (rigorous == null) {
            return true;
        } else {
            return rigorous;
        }
    }

    /**
     * Sets the value of the rigorous property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRigorous(Boolean value) {
        this.rigorous = value;
    }

    /**
     * Gets the value of the showAllFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isShowAllFlag() {
        if (showAllFlag == null) {
            return false;
        } else {
            return showAllFlag;
        }
    }

    /**
     * Sets the value of the showAllFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowAllFlag(Boolean value) {
        this.showAllFlag = value;
    }

    /**
     * Gets the value of the hiddenItemsVisibility property.
     * 
     * @return
     *     possible object is
     *     {@link HiddenItemsVisibilityEnum }
     *     
     */
    public HiddenItemsVisibilityEnum getHiddenItemsVisibility() {
        if (hiddenItemsVisibility == null) {
            return HiddenItemsVisibilityEnum.ITEMS_VISIBILITY_HIDDEN;
        } else {
            return hiddenItemsVisibility;
        }
    }

    /**
     * Sets the value of the hiddenItemsVisibility property.
     * 
     * @param value
     *     allowed object is
     *     {@link HiddenItemsVisibilityEnum }
     *     
     */
    public void setHiddenItemsVisibility(HiddenItemsVisibilityEnum value) {
        this.hiddenItemsVisibility = value;
    }

    /**
     * Gets the value of the showPages property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isShowPages() {
        if (showPages == null) {
            return false;
        } else {
            return showPages;
        }
    }

    /**
     * Sets the value of the showPages property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowPages(Boolean value) {
        this.showPages = value;
    }

    /**
     * Gets the value of the snapToGrid property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isSnapToGrid() {
        if (snapToGrid == null) {
            return false;
        } else {
            return snapToGrid;
        }
    }

    /**
     * Sets the value of the snapToGrid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSnapToGrid(Boolean value) {
        this.snapToGrid = value;
    }

    /**
     * Gets the value of the timeBarVisible property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isTimeBarVisible() {
        if (timeBarVisible == null) {
            return false;
        } else {
            return timeBarVisible;
        }
    }

    /**
     * Sets the value of the timeBarVisible property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTimeBarVisible(Boolean value) {
        this.timeBarVisible = value;
    }

    /**
     * Gets the value of the typeIconDrawingMode property.
     * 
     * @return
     *     possible object is
     *     {@link TypeIconDrawingModeEnum }
     *     
     */
    public TypeIconDrawingModeEnum getTypeIconDrawingMode() {
        if (typeIconDrawingMode == null) {
            return TypeIconDrawingModeEnum.HIGH_QUALITY;
        } else {
            return typeIconDrawingMode;
        }
    }

    /**
     * Sets the value of the typeIconDrawingMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeIconDrawingModeEnum }
     *     
     */
    public void setTypeIconDrawingMode(TypeIconDrawingModeEnum value) {
        this.typeIconDrawingMode = value;
    }

    /**
     * Gets the value of the useDefaultLinkSpacingWhenDragging property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isUseDefaultLinkSpacingWhenDragging() {
        if (useDefaultLinkSpacingWhenDragging == null) {
            return false;
        } else {
            return useDefaultLinkSpacingWhenDragging;
        }
    }

    /**
     * Sets the value of the useDefaultLinkSpacingWhenDragging property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUseDefaultLinkSpacingWhenDragging(Boolean value) {
        this.useDefaultLinkSpacingWhenDragging = value;
    }

    /**
     * Gets the value of the useLocalTimeZone property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isUseLocalTimeZone() {
        if (useLocalTimeZone == null) {
            return true;
        } else {
            return useLocalTimeZone;
        }
    }

    /**
     * Sets the value of the useLocalTimeZone property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUseLocalTimeZone(Boolean value) {
        this.useLocalTimeZone = value;
    }

    /**
     * Gets the value of the useWiringHeightForThemeIcon property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isUseWiringHeightForThemeIcon() {
        if (useWiringHeightForThemeIcon == null) {
            return true;
        } else {
            return useWiringHeightForThemeIcon;
        }
    }

    /**
     * Sets the value of the useWiringHeightForThemeIcon property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUseWiringHeightForThemeIcon(Boolean value) {
        this.useWiringHeightForThemeIcon = value;
    }

    /**
     * Gets the value of the wiringDistanceFar property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public double getWiringDistanceFar() {
        if (wiringDistanceFar == null) {
            return  0.393700787401575D;
        } else {
            return wiringDistanceFar;
        }
    }

    /**
     * Sets the value of the wiringDistanceFar property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setWiringDistanceFar(Double value) {
        this.wiringDistanceFar = value;
    }

    /**
     * Gets the value of the wiringDistanceNear property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public double getWiringDistanceNear() {
        if (wiringDistanceNear == null) {
            return  0.078740157480315D;
        } else {
            return wiringDistanceNear;
        }
    }

    /**
     * Sets the value of the wiringDistanceNear property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setWiringDistanceNear(Double value) {
        this.wiringDistanceNear = value;
    }

    /**
     * Gets the value of the wiringHeight property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public double getWiringHeight() {
        if (wiringHeight == null) {
            return  0.196850393700787D;
        } else {
            return wiringHeight;
        }
    }

    /**
     * Sets the value of the wiringHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setWiringHeight(Double value) {
        this.wiringHeight = value;
    }

    /**
     * Gets the value of the wiringSpacing property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public double getWiringSpacing() {
        if (wiringSpacing == null) {
            return  0.196850393700787D;
        } else {
            return wiringSpacing;
        }
    }

    /**
     * Sets the value of the wiringSpacing property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setWiringSpacing(Double value) {
        this.wiringSpacing = value;
    }

    /**
     * Gets the value of the coverSheetShowOnOpen property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCoverSheetShowOnOpen() {
        return coverSheetShowOnOpen;
    }

    /**
     * Sets the value of the coverSheetShowOnOpen property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCoverSheetShowOnOpen(Boolean value) {
        this.coverSheetShowOnOpen = value;
    }

}
