//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.08 at 09:29:27 PM CEST 
//


package edu.anb.core;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element ref="{}End"/>
 *           &lt;element ref="{}Link"/>
 *         &lt;/choice>
 *         &lt;element ref="{}AttributeCollection" minOccurs="0"/>
 *         &lt;element ref="{}CIStyle" minOccurs="0"/>
 *         &lt;element ref="{}PropertyBagCollection" minOccurs="0"/>
 *         &lt;element ref="{}TimeZone" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="DateSet" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="DateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="DateTimeDescription" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Description" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="GradeOneIndex" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *       &lt;attribute ref="{}GradeOneReference"/>
 *       &lt;attribute name="GradeThreeIndex" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *       &lt;attribute ref="{}GradeThreeReference"/>
 *       &lt;attribute name="GradeTwoIndex" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *       &lt;attribute ref="{}GradeTwoReference"/>
 *       &lt;attribute ref="{}Id"/>
 *       &lt;attribute ref="{}GroupReference"/>
 *       &lt;attribute name="Label" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="LocalDateTimeOffset" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="Ordered" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="Shown" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="Selected" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="SourceReference" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SourceType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="TimeSet" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="XPosition" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "end",
    "link",
    "attributeCollection",
    "ciStyle",
    "propertyBagCollection",
    "timeZone"
})
@XmlRootElement(name = "ChartItem")
public class ChartItem {

    @XmlElement(name = "End")
    protected End end;
    @XmlElement(name = "Link")
    protected Link link;
    @XmlElement(name = "AttributeCollection")
    protected AttributeCollection attributeCollection;
    @XmlElement(name = "CIStyle")
    protected CIStyle ciStyle;
    @XmlElement(name = "PropertyBagCollection")
    protected PropertyBagCollection propertyBagCollection;
    @XmlElement(name = "TimeZone")
    protected TimeZone timeZone;
    @XmlAttribute(name = "DateSet")
    protected Boolean dateSet;
    @XmlAttribute(name = "DateTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateTime;
    @XmlAttribute(name = "DateTimeDescription")
    protected java.lang.String dateTimeDescription;
    @XmlAttribute(name = "Description")
    protected java.lang.String description;
    @XmlAttribute(name = "GradeOneIndex")
    protected Integer gradeOneIndex;
    @XmlAttribute(name = "GradeOneReference")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object gradeOneReference;
    @XmlAttribute(name = "GradeThreeIndex")
    protected Integer gradeThreeIndex;
    @XmlAttribute(name = "GradeThreeReference")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object gradeThreeReference;
    @XmlAttribute(name = "GradeTwoIndex")
    protected Integer gradeTwoIndex;
    @XmlAttribute(name = "GradeTwoReference")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object gradeTwoReference;
    @XmlAttribute(name = "Id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected java.lang.String id;
    @XmlAttribute(name = "GroupReference")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object groupReference;
    @XmlAttribute(name = "Label")
    protected java.lang.String label;
    @XmlAttribute(name = "LocalDateTimeOffset")
    protected BigInteger localDateTimeOffset;
    @XmlAttribute(name = "Ordered")
    protected Boolean ordered;
    @XmlAttribute(name = "Shown")
    protected Boolean shown;
    @XmlAttribute(name = "Selected")
    protected Boolean selected;
    @XmlAttribute(name = "SourceReference")
    protected java.lang.String sourceReference;
    @XmlAttribute(name = "SourceType")
    protected java.lang.String sourceType;
    @XmlAttribute(name = "TimeSet")
    protected Boolean timeSet;
    @XmlAttribute(name = "XPosition")
    protected Integer xPosition;

    /**
     * Gets the value of the end property.
     * 
     * @return
     *     possible object is
     *     {@link End }
     *     
     */
    public End getEnd() {
        return end;
    }

    /**
     * Sets the value of the end property.
     * 
     * @param value
     *     allowed object is
     *     {@link End }
     *     
     */
    public void setEnd(End value) {
        this.end = value;
    }

    /**
     * Gets the value of the link property.
     * 
     * @return
     *     possible object is
     *     {@link Link }
     *     
     */
    public Link getLink() {
        return link;
    }

    /**
     * Sets the value of the link property.
     * 
     * @param value
     *     allowed object is
     *     {@link Link }
     *     
     */
    public void setLink(Link value) {
        this.link = value;
    }

    /**
     * Gets the value of the attributeCollection property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeCollection }
     *     
     */
    public AttributeCollection getAttributeCollection() {
        return attributeCollection;
    }

    /**
     * Sets the value of the attributeCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeCollection }
     *     
     */
    public void setAttributeCollection(AttributeCollection value) {
        this.attributeCollection = value;
    }

    /**
     * Gets the value of the ciStyle property.
     * 
     * @return
     *     possible object is
     *     {@link CIStyle }
     *     
     */
    public CIStyle getCIStyle() {
        return ciStyle;
    }

    /**
     * Sets the value of the ciStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link CIStyle }
     *     
     */
    public void setCIStyle(CIStyle value) {
        this.ciStyle = value;
    }

    /**
     * Gets the value of the propertyBagCollection property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyBagCollection }
     *     
     */
    public PropertyBagCollection getPropertyBagCollection() {
        return propertyBagCollection;
    }

    /**
     * Sets the value of the propertyBagCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyBagCollection }
     *     
     */
    public void setPropertyBagCollection(PropertyBagCollection value) {
        this.propertyBagCollection = value;
    }

    /**
     * Gets the value of the timeZone property.
     * 
     * @return
     *     possible object is
     *     {@link TimeZone }
     *     
     */
    public TimeZone getTimeZone() {
        return timeZone;
    }

    /**
     * Sets the value of the timeZone property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeZone }
     *     
     */
    public void setTimeZone(TimeZone value) {
        this.timeZone = value;
    }

    /**
     * Gets the value of the dateSet property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isDateSet() {
        if (dateSet == null) {
            return false;
        } else {
            return dateSet;
        }
    }

    /**
     * Sets the value of the dateSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDateSet(Boolean value) {
        this.dateSet = value;
    }

    /**
     * Gets the value of the dateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateTime() {
        return dateTime;
    }

    /**
     * Sets the value of the dateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateTime(XMLGregorianCalendar value) {
        this.dateTime = value;
    }

    /**
     * Gets the value of the dateTimeDescription property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getDateTimeDescription() {
        return dateTimeDescription;
    }

    /**
     * Sets the value of the dateTimeDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setDateTimeDescription(java.lang.String value) {
        this.dateTimeDescription = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setDescription(java.lang.String value) {
        this.description = value;
    }

    /**
     * Gets the value of the gradeOneIndex property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getGradeOneIndex() {
        if (gradeOneIndex == null) {
            return  0;
        } else {
            return gradeOneIndex;
        }
    }

    /**
     * Sets the value of the gradeOneIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setGradeOneIndex(Integer value) {
        this.gradeOneIndex = value;
    }

    /**
     * IDREF for the item's grade one in the chart's grading system.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getGradeOneReference() {
        return gradeOneReference;
    }

    /**
     * Sets the value of the gradeOneReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setGradeOneReference(Object value) {
        this.gradeOneReference = value;
    }

    /**
     * Gets the value of the gradeThreeIndex property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getGradeThreeIndex() {
        if (gradeThreeIndex == null) {
            return  0;
        } else {
            return gradeThreeIndex;
        }
    }

    /**
     * Sets the value of the gradeThreeIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setGradeThreeIndex(Integer value) {
        this.gradeThreeIndex = value;
    }

    /**
     * IDREF for the item's grade three in the chart's grading system.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getGradeThreeReference() {
        return gradeThreeReference;
    }

    /**
     * Sets the value of the gradeThreeReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setGradeThreeReference(Object value) {
        this.gradeThreeReference = value;
    }

    /**
     * Gets the value of the gradeTwoIndex property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getGradeTwoIndex() {
        if (gradeTwoIndex == null) {
            return  0;
        } else {
            return gradeTwoIndex;
        }
    }

    /**
     * Sets the value of the gradeTwoIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setGradeTwoIndex(Integer value) {
        this.gradeTwoIndex = value;
    }

    /**
     * IDREF for the item's grade two in the chart's grading system.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getGradeTwoReference() {
        return gradeTwoReference;
    }

    /**
     * Sets the value of the gradeTwoReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setGradeTwoReference(Object value) {
        this.gradeTwoReference = value;
    }

    /**
     * Chart item ID (see IdReferenceLinking).
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setId(java.lang.String value) {
        this.id = value;
    }

    /**
     * The IDREF of the item's group.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getGroupReference() {
        return groupReference;
    }

    /**
     * Sets the value of the groupReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setGroupReference(Object value) {
        this.groupReference = value;
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setLabel(java.lang.String value) {
        this.label = value;
    }

    /**
     * Gets the value of the localDateTimeOffset property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLocalDateTimeOffset() {
        return localDateTimeOffset;
    }

    /**
     * Sets the value of the localDateTimeOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLocalDateTimeOffset(BigInteger value) {
        this.localDateTimeOffset = value;
    }

    /**
     * Gets the value of the ordered property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isOrdered() {
        if (ordered == null) {
            return false;
        } else {
            return ordered;
        }
    }

    /**
     * Sets the value of the ordered property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOrdered(Boolean value) {
        this.ordered = value;
    }

    /**
     * Gets the value of the shown property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isShown() {
        return shown;
    }

    /**
     * Sets the value of the shown property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShown(Boolean value) {
        this.shown = value;
    }

    /**
     * Gets the value of the selected property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isSelected() {
        if (selected == null) {
            return false;
        } else {
            return selected;
        }
    }

    /**
     * Sets the value of the selected property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSelected(Boolean value) {
        this.selected = value;
    }

    /**
     * Gets the value of the sourceReference property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getSourceReference() {
        return sourceReference;
    }

    /**
     * Sets the value of the sourceReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setSourceReference(java.lang.String value) {
        this.sourceReference = value;
    }

    /**
     * Gets the value of the sourceType property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getSourceType() {
        return sourceType;
    }

    /**
     * Sets the value of the sourceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setSourceType(java.lang.String value) {
        this.sourceType = value;
    }

    /**
     * Gets the value of the timeSet property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isTimeSet() {
        if (timeSet == null) {
            return false;
        } else {
            return timeSet;
        }
    }

    /**
     * Sets the value of the timeSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTimeSet(Boolean value) {
        this.timeSet = value;
    }

    /**
     * Gets the value of the xPosition property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getXPosition() {
        if (xPosition == null) {
            return  0;
        } else {
            return xPosition;
        }
    }

    /**
     * Sets the value of the xPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setXPosition(Integer value) {
        this.xPosition = value;
    }

}
