//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.08 at 09:29:27 PM CEST 
//


package edu.anb.core;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="FanOut" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="Multiplicity" type="{}MultipleLinkStyleEnum" />
 *       &lt;attribute name="ThemeWiring" type="{}ThemeWiringOptionEnum" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "ConnectionStyle")
public class ConnectionStyle {

    @XmlAttribute(name = "FanOut")
    protected Integer fanOut;
    @XmlAttribute(name = "Multiplicity")
    protected MultipleLinkStyleEnum multiplicity;
    @XmlAttribute(name = "ThemeWiring")
    protected ThemeWiringOptionEnum themeWiring;

    /**
     * Gets the value of the fanOut property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFanOut() {
        return fanOut;
    }

    /**
     * Sets the value of the fanOut property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFanOut(Integer value) {
        this.fanOut = value;
    }

    /**
     * Gets the value of the multiplicity property.
     * 
     * @return
     *     possible object is
     *     {@link MultipleLinkStyleEnum }
     *     
     */
    public MultipleLinkStyleEnum getMultiplicity() {
        return multiplicity;
    }

    /**
     * Sets the value of the multiplicity property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultipleLinkStyleEnum }
     *     
     */
    public void setMultiplicity(MultipleLinkStyleEnum value) {
        this.multiplicity = value;
    }

    /**
     * Gets the value of the themeWiring property.
     * 
     * @return
     *     possible object is
     *     {@link ThemeWiringOptionEnum }
     *     
     */
    public ThemeWiringOptionEnum getThemeWiring() {
        return themeWiring;
    }

    /**
     * Sets the value of the themeWiring property.
     * 
     * @param value
     *     allowed object is
     *     {@link ThemeWiringOptionEnum }
     *     
     */
    public void setThemeWiring(ThemeWiringOptionEnum value) {
        this.themeWiring = value;
    }

}
