//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.08 at 09:29:27 PM CEST 
//


package edu.anb.core;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}CIStyle" minOccurs="0"/>
 *         &lt;element ref="{}CircleStyle" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ciStyle",
    "circleStyle"
})
@XmlRootElement(name = "CurrentCircleStyle")
public class CurrentCircleStyle {

    @XmlElement(name = "CIStyle")
    protected CIStyle ciStyle;
    @XmlElement(name = "CircleStyle")
    protected CircleStyle circleStyle;

    /**
     * Gets the value of the ciStyle property.
     * 
     * @return
     *     possible object is
     *     {@link CIStyle }
     *     
     */
    public CIStyle getCIStyle() {
        return ciStyle;
    }

    /**
     * Sets the value of the ciStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link CIStyle }
     *     
     */
    public void setCIStyle(CIStyle value) {
        this.ciStyle = value;
    }

    /**
     * Gets the value of the circleStyle property.
     * 
     * @return
     *     possible object is
     *     {@link CircleStyle }
     *     
     */
    public CircleStyle getCircleStyle() {
        return circleStyle;
    }

    /**
     * Sets the value of the circleStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link CircleStyle }
     *     
     */
    public void setCircleStyle(CircleStyle value) {
        this.circleStyle = value;
    }

}
