//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.08 at 09:29:27 PM CEST 
//


package edu.anb.core;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}ConnectionStyle" minOccurs="0"/>
 *         &lt;element ref="{}CurrentBoxStyle" minOccurs="0"/>
 *         &lt;element ref="{}CurrentCircleStyle" minOccurs="0"/>
 *         &lt;element ref="{}CurrentEventStyle" minOccurs="0"/>
 *         &lt;element ref="{}CurrentIconStyle" minOccurs="0"/>
 *         &lt;element ref="{}CurrentLabelStyle" minOccurs="0"/>
 *         &lt;element ref="{}CurrentLinkStyle" minOccurs="0"/>
 *         &lt;element ref="{}CurrentOleItemStyle" minOccurs="0"/>
 *         &lt;element ref="{}CurrentTextBlockStyle" minOccurs="0"/>
 *         &lt;element ref="{}CurrentThemeStyle" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "connectionStyle",
    "currentBoxStyle",
    "currentCircleStyle",
    "currentEventStyle",
    "currentIconStyle",
    "currentLabelStyle",
    "currentLinkStyle",
    "currentOleItemStyle",
    "currentTextBlockStyle",
    "currentThemeStyle"
})
@XmlRootElement(name = "CurrentStyleCollection")
public class CurrentStyleCollection {

    @XmlElement(name = "ConnectionStyle")
    protected ConnectionStyle connectionStyle;
    @XmlElement(name = "CurrentBoxStyle")
    protected CurrentBoxStyle currentBoxStyle;
    @XmlElement(name = "CurrentCircleStyle")
    protected CurrentCircleStyle currentCircleStyle;
    @XmlElement(name = "CurrentEventStyle")
    protected CurrentEventStyle currentEventStyle;
    @XmlElement(name = "CurrentIconStyle")
    protected CurrentIconStyle currentIconStyle;
    @XmlElement(name = "CurrentLabelStyle")
    protected CurrentLabelStyle currentLabelStyle;
    @XmlElement(name = "CurrentLinkStyle")
    protected CurrentLinkStyle currentLinkStyle;
    @XmlElement(name = "CurrentOleItemStyle")
    protected CurrentOleItemStyle currentOleItemStyle;
    @XmlElement(name = "CurrentTextBlockStyle")
    protected CurrentTextBlockStyle currentTextBlockStyle;
    @XmlElement(name = "CurrentThemeStyle")
    protected CurrentThemeStyle currentThemeStyle;

    /**
     * Gets the value of the connectionStyle property.
     * 
     * @return
     *     possible object is
     *     {@link ConnectionStyle }
     *     
     */
    public ConnectionStyle getConnectionStyle() {
        return connectionStyle;
    }

    /**
     * Sets the value of the connectionStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConnectionStyle }
     *     
     */
    public void setConnectionStyle(ConnectionStyle value) {
        this.connectionStyle = value;
    }

    /**
     * Gets the value of the currentBoxStyle property.
     * 
     * @return
     *     possible object is
     *     {@link CurrentBoxStyle }
     *     
     */
    public CurrentBoxStyle getCurrentBoxStyle() {
        return currentBoxStyle;
    }

    /**
     * Sets the value of the currentBoxStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrentBoxStyle }
     *     
     */
    public void setCurrentBoxStyle(CurrentBoxStyle value) {
        this.currentBoxStyle = value;
    }

    /**
     * Gets the value of the currentCircleStyle property.
     * 
     * @return
     *     possible object is
     *     {@link CurrentCircleStyle }
     *     
     */
    public CurrentCircleStyle getCurrentCircleStyle() {
        return currentCircleStyle;
    }

    /**
     * Sets the value of the currentCircleStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrentCircleStyle }
     *     
     */
    public void setCurrentCircleStyle(CurrentCircleStyle value) {
        this.currentCircleStyle = value;
    }

    /**
     * Gets the value of the currentEventStyle property.
     * 
     * @return
     *     possible object is
     *     {@link CurrentEventStyle }
     *     
     */
    public CurrentEventStyle getCurrentEventStyle() {
        return currentEventStyle;
    }

    /**
     * Sets the value of the currentEventStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrentEventStyle }
     *     
     */
    public void setCurrentEventStyle(CurrentEventStyle value) {
        this.currentEventStyle = value;
    }

    /**
     * Gets the value of the currentIconStyle property.
     * 
     * @return
     *     possible object is
     *     {@link CurrentIconStyle }
     *     
     */
    public CurrentIconStyle getCurrentIconStyle() {
        return currentIconStyle;
    }

    /**
     * Sets the value of the currentIconStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrentIconStyle }
     *     
     */
    public void setCurrentIconStyle(CurrentIconStyle value) {
        this.currentIconStyle = value;
    }

    /**
     * Gets the value of the currentLabelStyle property.
     * 
     * @return
     *     possible object is
     *     {@link CurrentLabelStyle }
     *     
     */
    public CurrentLabelStyle getCurrentLabelStyle() {
        return currentLabelStyle;
    }

    /**
     * Sets the value of the currentLabelStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrentLabelStyle }
     *     
     */
    public void setCurrentLabelStyle(CurrentLabelStyle value) {
        this.currentLabelStyle = value;
    }

    /**
     * Gets the value of the currentLinkStyle property.
     * 
     * @return
     *     possible object is
     *     {@link CurrentLinkStyle }
     *     
     */
    public CurrentLinkStyle getCurrentLinkStyle() {
        return currentLinkStyle;
    }

    /**
     * Sets the value of the currentLinkStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrentLinkStyle }
     *     
     */
    public void setCurrentLinkStyle(CurrentLinkStyle value) {
        this.currentLinkStyle = value;
    }

    /**
     * Gets the value of the currentOleItemStyle property.
     * 
     * @return
     *     possible object is
     *     {@link CurrentOleItemStyle }
     *     
     */
    public CurrentOleItemStyle getCurrentOleItemStyle() {
        return currentOleItemStyle;
    }

    /**
     * Sets the value of the currentOleItemStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrentOleItemStyle }
     *     
     */
    public void setCurrentOleItemStyle(CurrentOleItemStyle value) {
        this.currentOleItemStyle = value;
    }

    /**
     * Gets the value of the currentTextBlockStyle property.
     * 
     * @return
     *     possible object is
     *     {@link CurrentTextBlockStyle }
     *     
     */
    public CurrentTextBlockStyle getCurrentTextBlockStyle() {
        return currentTextBlockStyle;
    }

    /**
     * Sets the value of the currentTextBlockStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrentTextBlockStyle }
     *     
     */
    public void setCurrentTextBlockStyle(CurrentTextBlockStyle value) {
        this.currentTextBlockStyle = value;
    }

    /**
     * Gets the value of the currentThemeStyle property.
     * 
     * @return
     *     possible object is
     *     {@link CurrentThemeStyle }
     *     
     */
    public CurrentThemeStyle getCurrentThemeStyle() {
        return currentThemeStyle;
    }

    /**
     * Sets the value of the currentThemeStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrentThemeStyle }
     *     
     */
    public void setCurrentThemeStyle(CurrentThemeStyle value) {
        this.currentThemeStyle = value;
    }

}
