//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.08 at 09:29:27 PM CEST 
//


package edu.anb.core;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{}EntityObjects" minOccurs="0"/>
 *         &lt;element ref="{}LinkObjects" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ClassID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ClassName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ConnectString" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute ref="{}Id"/>
 *       &lt;attribute name="InstanceName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="DisplayName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="MultipleKeysEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "entityObjectsAndLinkObjects"
})
@XmlRootElement(name = "DatabaseProxy")
public class DatabaseProxy {

    @XmlElements({
        @XmlElement(name = "EntityObjects", type = EntityObjects.class),
        @XmlElement(name = "LinkObjects", type = LinkObjects.class)
    })
    protected List<Object> entityObjectsAndLinkObjects;
    @XmlAttribute(name = "ClassID", required = true)
    protected java.lang.String classID;
    @XmlAttribute(name = "ClassName", required = true)
    protected java.lang.String className;
    @XmlAttribute(name = "ConnectString")
    protected java.lang.String connectString;
    @XmlAttribute(name = "Id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected java.lang.String id;
    @XmlAttribute(name = "InstanceName", required = true)
    protected java.lang.String instanceName;
    @XmlAttribute(name = "DisplayName")
    protected java.lang.String displayName;
    @XmlAttribute(name = "MultipleKeysEnabled")
    protected Boolean multipleKeysEnabled;

    /**
     * Gets the value of the entityObjectsAndLinkObjects property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the entityObjectsAndLinkObjects property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEntityObjectsAndLinkObjects().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EntityObjects }
     * {@link LinkObjects }
     * 
     * 
     */
    public List<Object> getEntityObjectsAndLinkObjects() {
        if (entityObjectsAndLinkObjects == null) {
            entityObjectsAndLinkObjects = new ArrayList<Object>();
        }
        return this.entityObjectsAndLinkObjects;
    }

    /**
     * Gets the value of the classID property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getClassID() {
        return classID;
    }

    /**
     * Sets the value of the classID property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setClassID(java.lang.String value) {
        this.classID = value;
    }

    /**
     * Gets the value of the className property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getClassName() {
        return className;
    }

    /**
     * Sets the value of the className property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setClassName(java.lang.String value) {
        this.className = value;
    }

    /**
     * Gets the value of the connectString property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getConnectString() {
        return connectString;
    }

    /**
     * Sets the value of the connectString property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setConnectString(java.lang.String value) {
        this.connectString = value;
    }

    /**
     * Database proxy ID (see IdReferenceLinking).
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setId(java.lang.String value) {
        this.id = value;
    }

    /**
     * Gets the value of the instanceName property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getInstanceName() {
        return instanceName;
    }

    /**
     * Sets the value of the instanceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setInstanceName(java.lang.String value) {
        this.instanceName = value;
    }

    /**
     * Gets the value of the displayName property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getDisplayName() {
        return displayName;
    }

    /**
     * Sets the value of the displayName property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setDisplayName(java.lang.String value) {
        this.displayName = value;
    }

    /**
     * Gets the value of the multipleKeysEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isMultipleKeysEnabled() {
        if (multipleKeysEnabled == null) {
            return true;
        } else {
            return multipleKeysEnabled;
        }
    }

    /**
     * Sets the value of the multipleKeysEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMultipleKeysEnabled(Boolean value) {
        this.multipleKeysEnabled = value;
    }

}
