//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.08 at 09:29:27 PM CEST 
//


package edu.anb.core;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="DatabasePropertyType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute ref="{}DatabasePropertyTypeReference"/>
 *       &lt;attribute name="LocalDateTimeOffset" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="Value" type="{}AttributeValue" />
 *       &lt;attribute name="Visible" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "DatabaseProperty")
public class DatabaseProperty {

    @XmlAttribute(name = "DatabasePropertyType")
    protected java.lang.String databasePropertyType;
    @XmlAttribute(name = "DatabasePropertyTypeReference")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object databasePropertyTypeReference;
    @XmlAttribute(name = "LocalDateTimeOffset")
    protected BigInteger localDateTimeOffset;
    @XmlAttribute(name = "Value")
    protected java.lang.String value;
    @XmlAttribute(name = "Visible")
    protected Boolean visible;

    /**
     * Gets the value of the databasePropertyType property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getDatabasePropertyType() {
        return databasePropertyType;
    }

    /**
     * Sets the value of the databasePropertyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setDatabasePropertyType(java.lang.String value) {
        this.databasePropertyType = value;
    }

    /**
     * Database property type IDREF with which the database property is associated. Raises an error if the database property type is already assigned to another database property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getDatabasePropertyTypeReference() {
        return databasePropertyTypeReference;
    }

    /**
     * Sets the value of the databasePropertyTypeReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setDatabasePropertyTypeReference(Object value) {
        this.databasePropertyTypeReference = value;
    }

    /**
     * Gets the value of the localDateTimeOffset property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLocalDateTimeOffset() {
        return localDateTimeOffset;
    }

    /**
     * Sets the value of the localDateTimeOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLocalDateTimeOffset(BigInteger value) {
        this.localDateTimeOffset = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setValue(java.lang.String value) {
        this.value = value;
    }

    /**
     * Gets the value of the visible property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isVisible() {
        return visible;
    }

    /**
     * Sets the value of the visible property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVisible(Boolean value) {
        this.visible = value;
    }

}
