//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.08 at 09:29:27 PM CEST 
//


package edu.anb.core;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice minOccurs="0">
 *           &lt;element ref="{}Box"/>
 *           &lt;element ref="{}Circle"/>
 *           &lt;element ref="{}Event"/>
 *           &lt;element ref="{}Icon"/>
 *           &lt;element ref="{}OleItem"/>
 *           &lt;element ref="{}TextBlock"/>
 *           &lt;element ref="{}Theme"/>
 *         &lt;/choice>
 *         &lt;element ref="{}DatabaseKeyCollection" minOccurs="0"/>
 *         &lt;element ref="{}CardCollection" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="EntityId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Identity" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="LabelIsIdentity" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="SemanticTypeGuid" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "box",
    "circle",
    "event",
    "icon",
    "oleItem",
    "textBlock",
    "theme",
    "databaseKeyCollection",
    "cardCollection"
})
@XmlRootElement(name = "Entity")
public class Entity {

    @XmlElement(name = "Box")
    protected Box box;
    @XmlElement(name = "Circle")
    protected Circle circle;
    @XmlElement(name = "Event")
    protected Event event;
    @XmlElement(name = "Icon")
    protected Icon icon;
    @XmlElement(name = "OleItem")
    protected OleItem oleItem;
    @XmlElement(name = "TextBlock")
    protected TextBlock textBlock;
    @XmlElement(name = "Theme")
    protected Theme theme;
    @XmlElement(name = "DatabaseKeyCollection")
    protected DatabaseKeyCollection databaseKeyCollection;
    @XmlElement(name = "CardCollection")
    protected CardCollection cardCollection;
    @XmlAttribute(name = "EntityId")
    protected java.lang.String entityId;
    @XmlAttribute(name = "Identity")
    protected java.lang.String identity;
    @XmlAttribute(name = "LabelIsIdentity")
    protected Boolean labelIsIdentity;
    @XmlAttribute(name = "SemanticTypeGuid")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected java.lang.String semanticTypeGuid;

    /**
     * Gets the value of the box property.
     * 
     * @return
     *     possible object is
     *     {@link Box }
     *     
     */
    public Box getBox() {
        return box;
    }

    /**
     * Sets the value of the box property.
     * 
     * @param value
     *     allowed object is
     *     {@link Box }
     *     
     */
    public void setBox(Box value) {
        this.box = value;
    }

    /**
     * Gets the value of the circle property.
     * 
     * @return
     *     possible object is
     *     {@link Circle }
     *     
     */
    public Circle getCircle() {
        return circle;
    }

    /**
     * Sets the value of the circle property.
     * 
     * @param value
     *     allowed object is
     *     {@link Circle }
     *     
     */
    public void setCircle(Circle value) {
        this.circle = value;
    }

    /**
     * Gets the value of the event property.
     * 
     * @return
     *     possible object is
     *     {@link Event }
     *     
     */
    public Event getEvent() {
        return event;
    }

    /**
     * Sets the value of the event property.
     * 
     * @param value
     *     allowed object is
     *     {@link Event }
     *     
     */
    public void setEvent(Event value) {
        this.event = value;
    }

    /**
     * Gets the value of the icon property.
     * 
     * @return
     *     possible object is
     *     {@link Icon }
     *     
     */
    public Icon getIcon() {
        return icon;
    }

    /**
     * Sets the value of the icon property.
     * 
     * @param value
     *     allowed object is
     *     {@link Icon }
     *     
     */
    public void setIcon(Icon value) {
        this.icon = value;
    }

    /**
     * Gets the value of the oleItem property.
     * 
     * @return
     *     possible object is
     *     {@link OleItem }
     *     
     */
    public OleItem getOleItem() {
        return oleItem;
    }

    /**
     * Sets the value of the oleItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link OleItem }
     *     
     */
    public void setOleItem(OleItem value) {
        this.oleItem = value;
    }

    /**
     * Gets the value of the textBlock property.
     * 
     * @return
     *     possible object is
     *     {@link TextBlock }
     *     
     */
    public TextBlock getTextBlock() {
        return textBlock;
    }

    /**
     * Sets the value of the textBlock property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextBlock }
     *     
     */
    public void setTextBlock(TextBlock value) {
        this.textBlock = value;
    }

    /**
     * Gets the value of the theme property.
     * 
     * @return
     *     possible object is
     *     {@link Theme }
     *     
     */
    public Theme getTheme() {
        return theme;
    }

    /**
     * Sets the value of the theme property.
     * 
     * @param value
     *     allowed object is
     *     {@link Theme }
     *     
     */
    public void setTheme(Theme value) {
        this.theme = value;
    }

    /**
     * Gets the value of the databaseKeyCollection property.
     * 
     * @return
     *     possible object is
     *     {@link DatabaseKeyCollection }
     *     
     */
    public DatabaseKeyCollection getDatabaseKeyCollection() {
        return databaseKeyCollection;
    }

    /**
     * Sets the value of the databaseKeyCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatabaseKeyCollection }
     *     
     */
    public void setDatabaseKeyCollection(DatabaseKeyCollection value) {
        this.databaseKeyCollection = value;
    }

    /**
     * Gets the value of the cardCollection property.
     * 
     * @return
     *     possible object is
     *     {@link CardCollection }
     *     
     */
    public CardCollection getCardCollection() {
        return cardCollection;
    }

    /**
     * Sets the value of the cardCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link CardCollection }
     *     
     */
    public void setCardCollection(CardCollection value) {
        this.cardCollection = value;
    }

    /**
     * Gets the value of the entityId property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getEntityId() {
        return entityId;
    }

    /**
     * Sets the value of the entityId property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setEntityId(java.lang.String value) {
        this.entityId = value;
    }

    /**
     * Gets the value of the identity property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getIdentity() {
        return identity;
    }

    /**
     * Sets the value of the identity property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setIdentity(java.lang.String value) {
        this.identity = value;
    }

    /**
     * Gets the value of the labelIsIdentity property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isLabelIsIdentity() {
        if (labelIsIdentity == null) {
            return false;
        } else {
            return labelIsIdentity;
        }
    }

    /**
     * Sets the value of the labelIsIdentity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLabelIsIdentity(Boolean value) {
        this.labelIsIdentity = value;
    }

    /**
     * Gets the value of the semanticTypeGuid property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getSemanticTypeGuid() {
        return semanticTypeGuid;
    }

    /**
     * Sets the value of the semanticTypeGuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setSemanticTypeGuid(java.lang.String value) {
        this.semanticTypeGuid = value;
    }

}
