//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.08 at 09:29:27 PM CEST 
//


package edu.anb.core;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HeaderFooterPositionEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="HeaderFooterPositionEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="HeaderFooterPositionLeft"/>
 *     &lt;enumeration value="HeaderFooterPositionCenter"/>
 *     &lt;enumeration value="HeaderFooterPositionRight"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "HeaderFooterPositionEnum")
@XmlEnum
public enum HeaderFooterPositionEnum {


    /**
     * The header or footer element is aligned to the left of the page
     * 
     */
    @XmlEnumValue("HeaderFooterPositionLeft")
    HEADER_FOOTER_POSITION_LEFT("HeaderFooterPositionLeft"),

    /**
     * The header or footer element is aligned at the center of the page
     * 
     */
    @XmlEnumValue("HeaderFooterPositionCenter")
    HEADER_FOOTER_POSITION_CENTER("HeaderFooterPositionCenter"),

    /**
     * The header or footer element is aligned to the right of the page
     * 
     */
    @XmlEnumValue("HeaderFooterPositionRight")
    HEADER_FOOTER_POSITION_RIGHT("HeaderFooterPositionRight");
    private final java.lang.String value;

    HeaderFooterPositionEnum(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static HeaderFooterPositionEnum fromValue(java.lang.String v) {
        for (HeaderFooterPositionEnum c: HeaderFooterPositionEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
