//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.08 at 09:29:27 PM CEST 
//


package edu.anb.core;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HiddenItemsVisibilityEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="HiddenItemsVisibilityEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ItemsVisibilityHidden"/>
 *     &lt;enumeration value="ItemsVisibilityNormal"/>
 *     &lt;enumeration value="ItemsVisibilityGrayed"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "HiddenItemsVisibilityEnum")
@XmlEnum
public enum HiddenItemsVisibilityEnum {


    /**
     * Chart items marked as "not shown" are actually not visible
     * 
     */
    @XmlEnumValue("ItemsVisibilityHidden")
    ITEMS_VISIBILITY_HIDDEN("ItemsVisibilityHidden"),

    /**
     * Chart items marked as "not shown" are actually visible
     * 
     */
    @XmlEnumValue("ItemsVisibilityNormal")
    ITEMS_VISIBILITY_NORMAL("ItemsVisibilityNormal"),

    /**
     * Chart items marked as "not shown" are actually grayed out
     * 
     */
    @XmlEnumValue("ItemsVisibilityGrayed")
    ITEMS_VISIBILITY_GRAYED("ItemsVisibilityGrayed");
    private final java.lang.String value;

    HiddenItemsVisibilityEnum(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static HiddenItemsVisibilityEnum fromValue(java.lang.String v) {
        for (HiddenItemsVisibilityEnum c: HiddenItemsVisibilityEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
