//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.08 at 09:29:27 PM CEST 
//


package edu.anb.core;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="CustomSize" type="{http://www.w3.org/2001/XMLSchema}double" default="1.0" />
 *       &lt;attribute name="DataGuid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Data" type="{http://www.w3.org/2001/XMLSchema}base64Binary" />
 *       &lt;attribute name="DataLength" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="PictureSizeMethod" type="{}PictureSizeMethodEnum" default="UseEnlargement" />
 *       &lt;attribute name="Visible" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "IconPicture")
public class IconPicture {

    @XmlAttribute(name = "CustomSize")
    protected Double customSize;
    @XmlAttribute(name = "DataGuid")
    protected java.lang.String dataGuid;
    @XmlAttribute(name = "Data")
    protected byte[] data;
    @XmlAttribute(name = "DataLength")
    protected Integer dataLength;
    @XmlAttribute(name = "PictureSizeMethod")
    protected PictureSizeMethodEnum pictureSizeMethod;
    @XmlAttribute(name = "Visible")
    protected Boolean visible;

    /**
     * Gets the value of the customSize property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public double getCustomSize() {
        if (customSize == null) {
            return  1.0D;
        } else {
            return customSize;
        }
    }

    /**
     * Sets the value of the customSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setCustomSize(Double value) {
        this.customSize = value;
    }

    /**
     * Gets the value of the dataGuid property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getDataGuid() {
        return dataGuid;
    }

    /**
     * Sets the value of the dataGuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setDataGuid(java.lang.String value) {
        this.dataGuid = value;
    }

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setData(byte[] value) {
        this.data = value;
    }

    /**
     * Gets the value of the dataLength property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDataLength() {
        return dataLength;
    }

    /**
     * Sets the value of the dataLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDataLength(Integer value) {
        this.dataLength = value;
    }

    /**
     * Gets the value of the pictureSizeMethod property.
     * 
     * @return
     *     possible object is
     *     {@link PictureSizeMethodEnum }
     *     
     */
    public PictureSizeMethodEnum getPictureSizeMethod() {
        if (pictureSizeMethod == null) {
            return PictureSizeMethodEnum.USE_ENLARGEMENT;
        } else {
            return pictureSizeMethod;
        }
    }

    /**
     * Sets the value of the pictureSizeMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link PictureSizeMethodEnum }
     *     
     */
    public void setPictureSizeMethod(PictureSizeMethodEnum value) {
        this.pictureSizeMethod = value;
    }

    /**
     * Gets the value of the visible property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isVisible() {
        if (visible == null) {
            return false;
        } else {
            return visible;
        }
    }

    /**
     * Sets the value of the visible property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVisible(Boolean value) {
        this.visible = value;
    }

}
