//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.08 at 09:29:27 PM CEST 
//


package edu.anb.core;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="Colour" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="LineWidth" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="Strength" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute ref="{}StrengthReference"/>
 *       &lt;attribute name="ThemeColourAfter" type="{}JunctionOptionEnum" default="StyleCustom" />
 *       &lt;attribute name="ThemeLineWidthAfter" type="{}JunctionOptionEnum" default="StyleCustom" />
 *       &lt;attribute name="ThemeStrengthAfter" type="{}JunctionOptionEnum" default="StyleCustom" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "JunctionStyle")
public class JunctionStyle {

    @XmlAttribute(name = "Colour", required = true)
    protected int colour;
    @XmlAttribute(name = "LineWidth", required = true)
    protected int lineWidth;
    @XmlAttribute(name = "Strength", required = true)
    protected java.lang.String strength;
    @XmlAttribute(name = "StrengthReference")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object strengthReference;
    @XmlAttribute(name = "ThemeColourAfter")
    protected JunctionOptionEnum themeColourAfter;
    @XmlAttribute(name = "ThemeLineWidthAfter")
    protected JunctionOptionEnum themeLineWidthAfter;
    @XmlAttribute(name = "ThemeStrengthAfter")
    protected JunctionOptionEnum themeStrengthAfter;

    /**
     * Gets the value of the colour property.
     * 
     */
    public int getColour() {
        return colour;
    }

    /**
     * Sets the value of the colour property.
     * 
     */
    public void setColour(int value) {
        this.colour = value;
    }

    /**
     * Gets the value of the lineWidth property.
     * 
     */
    public int getLineWidth() {
        return lineWidth;
    }

    /**
     * Sets the value of the lineWidth property.
     * 
     */
    public void setLineWidth(int value) {
        this.lineWidth = value;
    }

    /**
     * Gets the value of the strength property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getStrength() {
        return strength;
    }

    /**
     * Sets the value of the strength property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setStrength(java.lang.String value) {
        this.strength = value;
    }

    /**
     * Strength IDREF of the theme line segment after this junction if ThemeStrengthAfter is set to StyleCustom.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getStrengthReference() {
        return strengthReference;
    }

    /**
     * Sets the value of the strengthReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setStrengthReference(Object value) {
        this.strengthReference = value;
    }

    /**
     * Gets the value of the themeColourAfter property.
     * 
     * @return
     *     possible object is
     *     {@link JunctionOptionEnum }
     *     
     */
    public JunctionOptionEnum getThemeColourAfter() {
        if (themeColourAfter == null) {
            return JunctionOptionEnum.STYLE_CUSTOM;
        } else {
            return themeColourAfter;
        }
    }

    /**
     * Sets the value of the themeColourAfter property.
     * 
     * @param value
     *     allowed object is
     *     {@link JunctionOptionEnum }
     *     
     */
    public void setThemeColourAfter(JunctionOptionEnum value) {
        this.themeColourAfter = value;
    }

    /**
     * Gets the value of the themeLineWidthAfter property.
     * 
     * @return
     *     possible object is
     *     {@link JunctionOptionEnum }
     *     
     */
    public JunctionOptionEnum getThemeLineWidthAfter() {
        if (themeLineWidthAfter == null) {
            return JunctionOptionEnum.STYLE_CUSTOM;
        } else {
            return themeLineWidthAfter;
        }
    }

    /**
     * Sets the value of the themeLineWidthAfter property.
     * 
     * @param value
     *     allowed object is
     *     {@link JunctionOptionEnum }
     *     
     */
    public void setThemeLineWidthAfter(JunctionOptionEnum value) {
        this.themeLineWidthAfter = value;
    }

    /**
     * Gets the value of the themeStrengthAfter property.
     * 
     * @return
     *     possible object is
     *     {@link JunctionOptionEnum }
     *     
     */
    public JunctionOptionEnum getThemeStrengthAfter() {
        if (themeStrengthAfter == null) {
            return JunctionOptionEnum.STYLE_CUSTOM;
        } else {
            return themeStrengthAfter;
        }
    }

    /**
     * Sets the value of the themeStrengthAfter property.
     * 
     * @param value
     *     allowed object is
     *     {@link JunctionOptionEnum }
     *     
     */
    public void setThemeStrengthAfter(JunctionOptionEnum value) {
        this.themeStrengthAfter = value;
    }

}
