//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.08 at 09:29:27 PM CEST 
//


package edu.anb.core;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}JunctionStyle"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "junctionStyle"
})
@XmlRootElement(name = "Junction")
public class Junction {

    @XmlElement(name = "JunctionStyle", required = true)
    protected JunctionStyle junctionStyle;

    /**
     * Gets the value of the junctionStyle property.
     * 
     * @return
     *     possible object is
     *     {@link JunctionStyle }
     *     
     */
    public JunctionStyle getJunctionStyle() {
        return junctionStyle;
    }

    /**
     * Sets the value of the junctionStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link JunctionStyle }
     *     
     */
    public void setJunctionStyle(JunctionStyle value) {
        this.junctionStyle = value;
    }

}
