//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.08 at 09:29:27 PM CEST 
//


package edu.anb.core;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LegendVerticalAlignmentEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LegendVerticalAlignmentEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="LegendAlignmentBottom"/>
 *     &lt;enumeration value="LegendAlignmentFree"/>
 *     &lt;enumeration value="LegendAlignmentTop"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "LegendVerticalAlignmentEnum")
@XmlEnum
public enum LegendVerticalAlignmentEnum {


    /**
     * The legend is aligned to the bottom extent of the chart.
     * 
     */
    @XmlEnumValue("LegendAlignmentBottom")
    LEGEND_ALIGNMENT_BOTTOM("LegendAlignmentBottom"),

    /**
     * The legend is unaligned vertically.
     * 
     */
    @XmlEnumValue("LegendAlignmentFree")
    LEGEND_ALIGNMENT_FREE("LegendAlignmentFree"),

    /**
     * The legend is aligned to the top extent of the chart.
     * 
     */
    @XmlEnumValue("LegendAlignmentTop")
    LEGEND_ALIGNMENT_TOP("LegendAlignmentTop");
    private final java.lang.String value;

    LegendVerticalAlignmentEnum(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static LegendVerticalAlignmentEnum fromValue(java.lang.String v) {
        for (LegendVerticalAlignmentEnum c: LegendVerticalAlignmentEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
