//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.08 at 09:29:27 PM CEST 
//


package edu.anb.core;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Font" minOccurs="0"/>
 *         &lt;element ref="{}LegendItem" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Arrange" type="{}LegendArrangementEnum" default="LegendArrangementSquare" />
 *       &lt;attribute name="HorizontalAlignment" type="{}LegendHorizontalAlignmentEnum" default="LegendAlignmentRight" />
 *       &lt;attribute name="Shown" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="VerticalAlignment" type="{}LegendVerticalAlignmentEnum" default="LegendAlignmentBottom" />
 *       &lt;attribute name="X" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *       &lt;attribute name="Y" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "font",
    "legendItem"
})
@XmlRootElement(name = "LegendDefinition")
public class LegendDefinition {

    @XmlElement(name = "Font")
    protected Font font;
    @XmlElement(name = "LegendItem")
    protected List<LegendItem> legendItem;
    @XmlAttribute(name = "Arrange")
    protected LegendArrangementEnum arrange;
    @XmlAttribute(name = "HorizontalAlignment")
    protected LegendHorizontalAlignmentEnum horizontalAlignment;
    @XmlAttribute(name = "Shown")
    protected Boolean shown;
    @XmlAttribute(name = "VerticalAlignment")
    protected LegendVerticalAlignmentEnum verticalAlignment;
    @XmlAttribute(name = "X")
    protected Integer x;
    @XmlAttribute(name = "Y")
    protected Integer y;

    /**
     * Gets the value of the font property.
     * 
     * @return
     *     possible object is
     *     {@link Font }
     *     
     */
    public Font getFont() {
        return font;
    }

    /**
     * Sets the value of the font property.
     * 
     * @param value
     *     allowed object is
     *     {@link Font }
     *     
     */
    public void setFont(Font value) {
        this.font = value;
    }

    /**
     * Gets the value of the legendItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the legendItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLegendItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LegendItem }
     * 
     * 
     */
    public List<LegendItem> getLegendItem() {
        if (legendItem == null) {
            legendItem = new ArrayList<LegendItem>();
        }
        return this.legendItem;
    }

    /**
     * Gets the value of the arrange property.
     * 
     * @return
     *     possible object is
     *     {@link LegendArrangementEnum }
     *     
     */
    public LegendArrangementEnum getArrange() {
        if (arrange == null) {
            return LegendArrangementEnum.LEGEND_ARRANGEMENT_SQUARE;
        } else {
            return arrange;
        }
    }

    /**
     * Sets the value of the arrange property.
     * 
     * @param value
     *     allowed object is
     *     {@link LegendArrangementEnum }
     *     
     */
    public void setArrange(LegendArrangementEnum value) {
        this.arrange = value;
    }

    /**
     * Gets the value of the horizontalAlignment property.
     * 
     * @return
     *     possible object is
     *     {@link LegendHorizontalAlignmentEnum }
     *     
     */
    public LegendHorizontalAlignmentEnum getHorizontalAlignment() {
        if (horizontalAlignment == null) {
            return LegendHorizontalAlignmentEnum.LEGEND_ALIGNMENT_RIGHT;
        } else {
            return horizontalAlignment;
        }
    }

    /**
     * Sets the value of the horizontalAlignment property.
     * 
     * @param value
     *     allowed object is
     *     {@link LegendHorizontalAlignmentEnum }
     *     
     */
    public void setHorizontalAlignment(LegendHorizontalAlignmentEnum value) {
        this.horizontalAlignment = value;
    }

    /**
     * Gets the value of the shown property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isShown() {
        if (shown == null) {
            return true;
        } else {
            return shown;
        }
    }

    /**
     * Sets the value of the shown property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShown(Boolean value) {
        this.shown = value;
    }

    /**
     * Gets the value of the verticalAlignment property.
     * 
     * @return
     *     possible object is
     *     {@link LegendVerticalAlignmentEnum }
     *     
     */
    public LegendVerticalAlignmentEnum getVerticalAlignment() {
        if (verticalAlignment == null) {
            return LegendVerticalAlignmentEnum.LEGEND_ALIGNMENT_BOTTOM;
        } else {
            return verticalAlignment;
        }
    }

    /**
     * Sets the value of the verticalAlignment property.
     * 
     * @param value
     *     allowed object is
     *     {@link LegendVerticalAlignmentEnum }
     *     
     */
    public void setVerticalAlignment(LegendVerticalAlignmentEnum value) {
        this.verticalAlignment = value;
    }

    /**
     * Gets the value of the x property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getX() {
        if (x == null) {
            return  0;
        } else {
            return x;
        }
    }

    /**
     * Sets the value of the x property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setX(Integer value) {
        this.x = value;
    }

    /**
     * Gets the value of the y property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getY() {
        if (y == null) {
            return  0;
        } else {
            return y;
        }
    }

    /**
     * Sets the value of the y property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setY(Integer value) {
        this.y = value;
    }

}
