//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.08 at 09:29:27 PM CEST 
//


package edu.anb.core;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Font" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="IconShadingColour" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="Arrows" type="{}ArrowStyleEnum" default="ArrowNone" />
 *       &lt;attribute name="Colour" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *       &lt;attribute name="DashStyle" type="{}DotStyleEnum" default="DotStyleSolid" />
 *       &lt;attribute name="ImageName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Label" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="LineWidth" type="{http://www.w3.org/2001/XMLSchema}int" default="1" />
 *       &lt;attribute name="Type" use="required" type="{}LegendItemTypeEnum" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "font"
})
@XmlRootElement(name = "LegendItem")
public class LegendItem {

    @XmlElement(name = "Font")
    protected Font font;
    @XmlAttribute(name = "IconShadingColour")
    protected Long iconShadingColour;
    @XmlAttribute(name = "Arrows")
    protected ArrowStyleEnum arrows;
    @XmlAttribute(name = "Colour")
    protected Integer colour;
    @XmlAttribute(name = "DashStyle")
    protected DotStyleEnum dashStyle;
    @XmlAttribute(name = "ImageName")
    protected java.lang.String imageName;
    @XmlAttribute(name = "Label")
    protected java.lang.String label;
    @XmlAttribute(name = "LineWidth")
    protected Integer lineWidth;
    @XmlAttribute(name = "Type", required = true)
    protected LegendItemTypeEnum type;

    /**
     * Gets the value of the font property.
     * 
     * @return
     *     possible object is
     *     {@link Font }
     *     
     */
    public Font getFont() {
        return font;
    }

    /**
     * Sets the value of the font property.
     * 
     * @param value
     *     allowed object is
     *     {@link Font }
     *     
     */
    public void setFont(Font value) {
        this.font = value;
    }

    /**
     * Gets the value of the iconShadingColour property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getIconShadingColour() {
        return iconShadingColour;
    }

    /**
     * Sets the value of the iconShadingColour property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setIconShadingColour(Long value) {
        this.iconShadingColour = value;
    }

    /**
     * Gets the value of the arrows property.
     * 
     * @return
     *     possible object is
     *     {@link ArrowStyleEnum }
     *     
     */
    public ArrowStyleEnum getArrows() {
        if (arrows == null) {
            return ArrowStyleEnum.ARROW_NONE;
        } else {
            return arrows;
        }
    }

    /**
     * Sets the value of the arrows property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrowStyleEnum }
     *     
     */
    public void setArrows(ArrowStyleEnum value) {
        this.arrows = value;
    }

    /**
     * Gets the value of the colour property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getColour() {
        if (colour == null) {
            return  0;
        } else {
            return colour;
        }
    }

    /**
     * Sets the value of the colour property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setColour(Integer value) {
        this.colour = value;
    }

    /**
     * Gets the value of the dashStyle property.
     * 
     * @return
     *     possible object is
     *     {@link DotStyleEnum }
     *     
     */
    public DotStyleEnum getDashStyle() {
        if (dashStyle == null) {
            return DotStyleEnum.DOT_STYLE_SOLID;
        } else {
            return dashStyle;
        }
    }

    /**
     * Sets the value of the dashStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link DotStyleEnum }
     *     
     */
    public void setDashStyle(DotStyleEnum value) {
        this.dashStyle = value;
    }

    /**
     * Gets the value of the imageName property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getImageName() {
        return imageName;
    }

    /**
     * Sets the value of the imageName property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setImageName(java.lang.String value) {
        this.imageName = value;
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setLabel(java.lang.String value) {
        this.label = value;
    }

    /**
     * Gets the value of the lineWidth property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getLineWidth() {
        if (lineWidth == null) {
            return  1;
        } else {
            return lineWidth;
        }
    }

    /**
     * Sets the value of the lineWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLineWidth(Integer value) {
        this.lineWidth = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link LegendItemTypeEnum }
     *     
     */
    public LegendItemTypeEnum getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link LegendItemTypeEnum }
     *     
     */
    public void setType(LegendItemTypeEnum value) {
        this.type = value;
    }

}
