//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.08 at 09:29:27 PM CEST 
//


package edu.anb.core;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LegendItemTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LegendItemTypeEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="LegendItemTypeAttribute"/>
 *     &lt;enumeration value="LegendItemTypeFont"/>
 *     &lt;enumeration value="LegendItemTypeIcon"/>
 *     &lt;enumeration value="LegendItemTypeLine"/>
 *     &lt;enumeration value="LegendItemTypeLink"/>
 *     &lt;enumeration value="LegendItemTypeText"/>
 *     &lt;enumeration value="LegendItemTypeTimeZone"/>
 *     &lt;enumeration value="LegendItemTypeIconFrame"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "LegendItemTypeEnum")
@XmlEnum
public enum LegendItemTypeEnum {


    /**
     * Attribute class item.
     * 
     */
    @XmlEnumValue("LegendItemTypeAttribute")
    LEGEND_ITEM_TYPE_ATTRIBUTE("LegendItemTypeAttribute"),

    /**
     * Font item.
     * 
     */
    @XmlEnumValue("LegendItemTypeFont")
    LEGEND_ITEM_TYPE_FONT("LegendItemTypeFont"),

    /**
     * Icon item.
     * 
     */
    @XmlEnumValue("LegendItemTypeIcon")
    LEGEND_ITEM_TYPE_ICON("LegendItemTypeIcon"),

    /**
     * Line item.
     * 
     */
    @XmlEnumValue("LegendItemTypeLine")
    LEGEND_ITEM_TYPE_LINE("LegendItemTypeLine"),

    /**
     * Link item.
     * 
     */
    @XmlEnumValue("LegendItemTypeLink")
    LEGEND_ITEM_TYPE_LINK("LegendItemTypeLink"),

    /**
     * Text item.
     * 
     */
    @XmlEnumValue("LegendItemTypeText")
    LEGEND_ITEM_TYPE_TEXT("LegendItemTypeText"),

    /**
     * TimeZone item.
     * 
     */
    @XmlEnumValue("LegendItemTypeTimeZone")
    LEGEND_ITEM_TYPE_TIME_ZONE("LegendItemTypeTimeZone"),

    /**
     * IconFrame item.
     * 
     */
    @XmlEnumValue("LegendItemTypeIconFrame")
    LEGEND_ITEM_TYPE_ICON_FRAME("LegendItemTypeIconFrame");
    private final java.lang.String value;

    LegendItemTypeEnum(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static LegendItemTypeEnum fromValue(java.lang.String v) {
        for (LegendItemTypeEnum c: LegendItemTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
