//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.08 at 09:29:27 PM CEST 
//


package edu.anb.core;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LibraryCatalogueType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LibraryCatalogueType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.i2group.com/Schemas/2001-12-07/LCXSchema}Type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.i2group.com/Schemas/2001-12-07/LCXSchema}Property" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.i2group.com/Schemas/2001-12-07/LCXSchema}Form" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.i2group.com/Schemas/2001-12-07/LCXSchema}Domain" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.i2group.com/Schemas/2001-12-07/LCXSchema}SectorDefinition" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="VersionMajor" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="VersionMinor" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="VersionRelease" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="VersionBuild" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="LocaleHex" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="LocaleVersion" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LibraryCatalogueType", namespace = "http://www.i2group.com/Schemas/2001-12-07/LCXSchema", propOrder = {
    "type",
    "property",
    "form",
    "domain",
    "sectorDefinition"
})
public class LibraryCatalogueType {

    @XmlElement(name = "Type", namespace = "http://www.i2group.com/Schemas/2001-12-07/LCXSchema")
    protected List<TypeType> type;
    @XmlElement(name = "Property", namespace = "http://www.i2group.com/Schemas/2001-12-07/LCXSchema")
    protected List<PropertyType> property;
    @XmlElement(name = "Form", namespace = "http://www.i2group.com/Schemas/2001-12-07/LCXSchema")
    protected List<FormType> form;
    @XmlElement(name = "Domain", namespace = "http://www.i2group.com/Schemas/2001-12-07/LCXSchema")
    protected List<DomainType> domain;
    @XmlElement(name = "SectorDefinition", namespace = "http://www.i2group.com/Schemas/2001-12-07/LCXSchema")
    protected List<SectorDefinition> sectorDefinition;
    @XmlAttribute(name = "VersionMajor", required = true)
    protected BigInteger versionMajor;
    @XmlAttribute(name = "VersionMinor", required = true)
    protected BigInteger versionMinor;
    @XmlAttribute(name = "VersionRelease", required = true)
    protected BigInteger versionRelease;
    @XmlAttribute(name = "VersionBuild", required = true)
    protected BigInteger versionBuild;
    @XmlAttribute(name = "LocaleHex", required = true)
    protected java.lang.String localeHex;
    @XmlAttribute(name = "LocaleVersion")
    protected BigInteger localeVersion;

    /**
     * Gets the value of the type property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the type property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TypeType }
     * 
     * 
     */
    public List<TypeType> getType() {
        if (type == null) {
            type = new ArrayList<TypeType>();
        }
        return this.type;
    }

    /**
     * Gets the value of the property property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the property property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProperty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PropertyType }
     * 
     * 
     */
    public List<PropertyType> getProperty() {
        if (property == null) {
            property = new ArrayList<PropertyType>();
        }
        return this.property;
    }

    /**
     * Gets the value of the form property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the form property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getForm().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FormType }
     * 
     * 
     */
    public List<FormType> getForm() {
        if (form == null) {
            form = new ArrayList<FormType>();
        }
        return this.form;
    }

    /**
     * Gets the value of the domain property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the domain property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDomain().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DomainType }
     * 
     * 
     */
    public List<DomainType> getDomain() {
        if (domain == null) {
            domain = new ArrayList<DomainType>();
        }
        return this.domain;
    }

    /**
     * Gets the value of the sectorDefinition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sectorDefinition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSectorDefinition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SectorDefinition }
     * 
     * 
     */
    public List<SectorDefinition> getSectorDefinition() {
        if (sectorDefinition == null) {
            sectorDefinition = new ArrayList<SectorDefinition>();
        }
        return this.sectorDefinition;
    }

    /**
     * Gets the value of the versionMajor property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVersionMajor() {
        return versionMajor;
    }

    /**
     * Sets the value of the versionMajor property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVersionMajor(BigInteger value) {
        this.versionMajor = value;
    }

    /**
     * Gets the value of the versionMinor property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVersionMinor() {
        return versionMinor;
    }

    /**
     * Sets the value of the versionMinor property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVersionMinor(BigInteger value) {
        this.versionMinor = value;
    }

    /**
     * Gets the value of the versionRelease property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVersionRelease() {
        return versionRelease;
    }

    /**
     * Sets the value of the versionRelease property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVersionRelease(BigInteger value) {
        this.versionRelease = value;
    }

    /**
     * Gets the value of the versionBuild property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVersionBuild() {
        return versionBuild;
    }

    /**
     * Sets the value of the versionBuild property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVersionBuild(BigInteger value) {
        this.versionBuild = value;
    }

    /**
     * Gets the value of the localeHex property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getLocaleHex() {
        return localeHex;
    }

    /**
     * Sets the value of the localeHex property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setLocaleHex(java.lang.String value) {
        this.localeHex = value;
    }

    /**
     * Gets the value of the localeVersion property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLocaleVersion() {
        return localeVersion;
    }

    /**
     * Sets the value of the localeVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLocaleVersion(BigInteger value) {
        this.localeVersion = value;
    }

}
