//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.08 at 09:29:27 PM CEST 
//


package edu.anb.core;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="LinkType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute ref="{}LinkTypeReference"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "LinkTypeEntry")
public class LinkTypeEntry {

    @XmlAttribute(name = "LinkType")
    protected java.lang.String linkType;
    @XmlAttribute(name = "LinkTypeReference")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object linkTypeReference;

    /**
     * Gets the value of the linkType property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getLinkType() {
        return linkType;
    }

    /**
     * Sets the value of the linkType property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setLinkType(java.lang.String value) {
        this.linkType = value;
    }

    /**
     * Type IDREF of link used by this entry. A link type is a category of link.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getLinkTypeReference() {
        return linkTypeReference;
    }

    /**
     * Sets the value of the linkTypeReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setLinkTypeReference(Object value) {
        this.linkTypeReference = value;
    }

}
