//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.08 at 09:29:27 PM CEST 
//


package edu.anb.core;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}DatabaseKeyCollection" minOccurs="0"/>
 *         &lt;element ref="{}CardCollection" minOccurs="0"/>
 *         &lt;element ref="{}CornerCollection" minOccurs="0"/>
 *         &lt;element ref="{}LinkStyle" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute ref="{}ConnectionReference"/>
 *       &lt;attribute name="End1Id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute ref="{}End1Reference"/>
 *       &lt;attribute name="End2Id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute ref="{}End2Reference"/>
 *       &lt;attribute name="LabelPos" type="{http://www.w3.org/2001/XMLSchema}int" default="50" />
 *       &lt;attribute name="LabelSegment" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *       &lt;attribute name="Offset" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="SemanticTypeGuid" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "databaseKeyCollection",
    "cardCollection",
    "cornerCollection",
    "linkStyle"
})
@XmlRootElement(name = "Link")
public class Link {

    @XmlElement(name = "DatabaseKeyCollection")
    protected DatabaseKeyCollection databaseKeyCollection;
    @XmlElement(name = "CardCollection")
    protected CardCollection cardCollection;
    @XmlElement(name = "CornerCollection")
    protected CornerCollection cornerCollection;
    @XmlElement(name = "LinkStyle")
    protected LinkStyle linkStyle;
    @XmlAttribute(name = "ConnectionReference")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object connectionReference;
    @XmlAttribute(name = "End1Id")
    protected java.lang.String end1Id;
    @XmlAttribute(name = "End1Reference")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object end1Reference;
    @XmlAttribute(name = "End2Id")
    protected java.lang.String end2Id;
    @XmlAttribute(name = "End2Reference")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object end2Reference;
    @XmlAttribute(name = "LabelPos")
    protected Integer labelPos;
    @XmlAttribute(name = "LabelSegment")
    protected Integer labelSegment;
    @XmlAttribute(name = "Offset")
    protected Integer offset;
    @XmlAttribute(name = "SemanticTypeGuid")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected java.lang.String semanticTypeGuid;

    /**
     * Gets the value of the databaseKeyCollection property.
     * 
     * @return
     *     possible object is
     *     {@link DatabaseKeyCollection }
     *     
     */
    public DatabaseKeyCollection getDatabaseKeyCollection() {
        return databaseKeyCollection;
    }

    /**
     * Sets the value of the databaseKeyCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatabaseKeyCollection }
     *     
     */
    public void setDatabaseKeyCollection(DatabaseKeyCollection value) {
        this.databaseKeyCollection = value;
    }

    /**
     * Gets the value of the cardCollection property.
     * 
     * @return
     *     possible object is
     *     {@link CardCollection }
     *     
     */
    public CardCollection getCardCollection() {
        return cardCollection;
    }

    /**
     * Sets the value of the cardCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link CardCollection }
     *     
     */
    public void setCardCollection(CardCollection value) {
        this.cardCollection = value;
    }

    /**
     * Gets the value of the cornerCollection property.
     * 
     * @return
     *     possible object is
     *     {@link CornerCollection }
     *     
     */
    public CornerCollection getCornerCollection() {
        return cornerCollection;
    }

    /**
     * Sets the value of the cornerCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link CornerCollection }
     *     
     */
    public void setCornerCollection(CornerCollection value) {
        this.cornerCollection = value;
    }

    /**
     * Gets the value of the linkStyle property.
     * 
     * @return
     *     possible object is
     *     {@link LinkStyle }
     *     
     */
    public LinkStyle getLinkStyle() {
        return linkStyle;
    }

    /**
     * Sets the value of the linkStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link LinkStyle }
     *     
     */
    public void setLinkStyle(LinkStyle value) {
        this.linkStyle = value;
    }

    /**
     * Connection IDREF that the link is part of.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getConnectionReference() {
        return connectionReference;
    }

    /**
     * Sets the value of the connectionReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setConnectionReference(Object value) {
        this.connectionReference = value;
    }

    /**
     * Gets the value of the end1Id property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getEnd1Id() {
        return end1Id;
    }

    /**
     * Sets the value of the end1Id property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setEnd1Id(java.lang.String value) {
        this.end1Id = value;
    }

    /**
     * One end IDREF of the connection.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getEnd1Reference() {
        return end1Reference;
    }

    /**
     * Sets the value of the end1Reference property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setEnd1Reference(Object value) {
        this.end1Reference = value;
    }

    /**
     * Gets the value of the end2Id property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getEnd2Id() {
        return end2Id;
    }

    /**
     * Sets the value of the end2Id property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setEnd2Id(java.lang.String value) {
        this.end2Id = value;
    }

    /**
     * Other end IDREF of the connection.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getEnd2Reference() {
        return end2Reference;
    }

    /**
     * Sets the value of the end2Reference property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setEnd2Reference(Object value) {
        this.end2Reference = value;
    }

    /**
     * Gets the value of the labelPos property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getLabelPos() {
        if (labelPos == null) {
            return  50;
        } else {
            return labelPos;
        }
    }

    /**
     * Sets the value of the labelPos property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLabelPos(Integer value) {
        this.labelPos = value;
    }

    /**
     * Gets the value of the labelSegment property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getLabelSegment() {
        if (labelSegment == null) {
            return  0;
        } else {
            return labelSegment;
        }
    }

    /**
     * Sets the value of the labelSegment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLabelSegment(Integer value) {
        this.labelSegment = value;
    }

    /**
     * Gets the value of the offset property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getOffset() {
        return offset;
    }

    /**
     * Sets the value of the offset property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setOffset(Integer value) {
        this.offset = value;
    }

    /**
     * Gets the value of the semanticTypeGuid property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getSemanticTypeGuid() {
        return semanticTypeGuid;
    }

    /**
     * Sets the value of the semanticTypeGuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setSemanticTypeGuid(java.lang.String value) {
        this.semanticTypeGuid = value;
    }

}
