//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.08 at 09:29:27 PM CEST 
//


package edu.anb.core;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute ref="{}EntityTypeReference"/>
 *       &lt;attribute name="LineWidth" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="ShowAsIcon" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="ShowFrame" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="Strength" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute ref="{}StrengthReference"/>
 *       &lt;attribute name="Type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "OleItemStyle")
public class OleItemStyle {

    @XmlAttribute(name = "EntityTypeReference")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object entityTypeReference;
    @XmlAttribute(name = "LineWidth")
    protected Integer lineWidth;
    @XmlAttribute(name = "ShowAsIcon")
    protected Boolean showAsIcon;
    @XmlAttribute(name = "ShowFrame")
    protected Boolean showFrame;
    @XmlAttribute(name = "Strength")
    protected java.lang.String strength;
    @XmlAttribute(name = "StrengthReference")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object strengthReference;
    @XmlAttribute(name = "Type")
    protected java.lang.String type;

    /**
     * Type IDREF of entity used by this style. An entity type is a category of entity.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getEntityTypeReference() {
        return entityTypeReference;
    }

    /**
     * Sets the value of the entityTypeReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setEntityTypeReference(Object value) {
        this.entityTypeReference = value;
    }

    /**
     * Gets the value of the lineWidth property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLineWidth() {
        return lineWidth;
    }

    /**
     * Sets the value of the lineWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLineWidth(Integer value) {
        this.lineWidth = value;
    }

    /**
     * Gets the value of the showAsIcon property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isShowAsIcon() {
        return showAsIcon;
    }

    /**
     * Sets the value of the showAsIcon property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowAsIcon(Boolean value) {
        this.showAsIcon = value;
    }

    /**
     * Gets the value of the showFrame property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isShowFrame() {
        return showFrame;
    }

    /**
     * Sets the value of the showFrame property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowFrame(Boolean value) {
        this.showFrame = value;
    }

    /**
     * Gets the value of the strength property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getStrength() {
        return strength;
    }

    /**
     * Sets the value of the strength property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setStrength(java.lang.String value) {
        this.strength = value;
    }

    /**
     * Strength IDREF associated with the OLE object, which controls the OLE object border appearance.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getStrengthReference() {
        return strengthReference;
    }

    /**
     * Sets the value of the strengthReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setStrengthReference(Object value) {
        this.strengthReference = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setType(java.lang.String value) {
        this.type = value;
    }

}
