//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.08 at 09:29:27 PM CEST 
//


package edu.anb.core;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}OleItemStyle" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="DataGuid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Data" type="{http://www.w3.org/2001/XMLSchema}base64Binary" />
 *       &lt;attribute name="DataLength" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" default="0" />
 *       &lt;attribute name="Height" type="{http://www.w3.org/2001/XMLSchema}int" default="100" />
 *       &lt;attribute name="IsCompressed" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="IsLinked" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="Path" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ProgID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="TextX" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *       &lt;attribute name="TextY" type="{http://www.w3.org/2001/XMLSchema}int" default="3" />
 *       &lt;attribute name="Width" type="{http://www.w3.org/2001/XMLSchema}int" default="100" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "oleItemStyle"
})
@XmlRootElement(name = "OleItem")
public class OleItem {

    @XmlElement(name = "OleItemStyle")
    protected OleItemStyle oleItemStyle;
    @XmlAttribute(name = "DataGuid")
    protected java.lang.String dataGuid;
    @XmlAttribute(name = "Data")
    protected byte[] data;
    @XmlAttribute(name = "DataLength")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger dataLength;
    @XmlAttribute(name = "Height")
    protected Integer height;
    @XmlAttribute(name = "IsCompressed")
    protected Boolean isCompressed;
    @XmlAttribute(name = "IsLinked")
    protected Boolean isLinked;
    @XmlAttribute(name = "Path")
    protected java.lang.String path;
    @XmlAttribute(name = "ProgID")
    protected java.lang.String progID;
    @XmlAttribute(name = "TextX")
    protected Integer textX;
    @XmlAttribute(name = "TextY")
    protected Integer textY;
    @XmlAttribute(name = "Width")
    protected Integer width;

    /**
     * Gets the value of the oleItemStyle property.
     * 
     * @return
     *     possible object is
     *     {@link OleItemStyle }
     *     
     */
    public OleItemStyle getOleItemStyle() {
        return oleItemStyle;
    }

    /**
     * Sets the value of the oleItemStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link OleItemStyle }
     *     
     */
    public void setOleItemStyle(OleItemStyle value) {
        this.oleItemStyle = value;
    }

    /**
     * Gets the value of the dataGuid property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getDataGuid() {
        return dataGuid;
    }

    /**
     * Sets the value of the dataGuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setDataGuid(java.lang.String value) {
        this.dataGuid = value;
    }

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setData(byte[] value) {
        this.data = value;
    }

    /**
     * Gets the value of the dataLength property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDataLength() {
        if (dataLength == null) {
            return new BigInteger("0");
        } else {
            return dataLength;
        }
    }

    /**
     * Sets the value of the dataLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDataLength(BigInteger value) {
        this.dataLength = value;
    }

    /**
     * Gets the value of the height property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getHeight() {
        if (height == null) {
            return  100;
        } else {
            return height;
        }
    }

    /**
     * Sets the value of the height property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setHeight(Integer value) {
        this.height = value;
    }

    /**
     * Gets the value of the isCompressed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIsCompressed() {
        if (isCompressed == null) {
            return false;
        } else {
            return isCompressed;
        }
    }

    /**
     * Sets the value of the isCompressed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsCompressed(Boolean value) {
        this.isCompressed = value;
    }

    /**
     * Gets the value of the isLinked property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIsLinked() {
        if (isLinked == null) {
            return false;
        } else {
            return isLinked;
        }
    }

    /**
     * Sets the value of the isLinked property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsLinked(Boolean value) {
        this.isLinked = value;
    }

    /**
     * Gets the value of the path property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getPath() {
        return path;
    }

    /**
     * Sets the value of the path property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setPath(java.lang.String value) {
        this.path = value;
    }

    /**
     * Gets the value of the progID property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getProgID() {
        return progID;
    }

    /**
     * Sets the value of the progID property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setProgID(java.lang.String value) {
        this.progID = value;
    }

    /**
     * Gets the value of the textX property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getTextX() {
        if (textX == null) {
            return  0;
        } else {
            return textX;
        }
    }

    /**
     * Sets the value of the textX property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTextX(Integer value) {
        this.textX = value;
    }

    /**
     * Gets the value of the textY property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getTextY() {
        if (textY == null) {
            return  3;
        } else {
            return textY;
        }
    }

    /**
     * Sets the value of the textY property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTextY(Integer value) {
        this.textY = value;
    }

    /**
     * Gets the value of the width property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getWidth() {
        if (width == null) {
            return  100;
        } else {
            return width;
        }
    }

    /**
     * Sets the value of the width property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setWidth(Integer value) {
        this.width = value;
    }

}
