//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.08 at 09:29:27 PM CEST 
//


package edu.anb.core;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="BottomMargin" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="LeftMargin" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="Orientation" type="{}PrintOrientationEnum" />
 *       &lt;attribute name="PaperSize" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="PaperSizeString" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Reduction" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="RightMargin" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="TopMargin" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="ThemeNameWidth" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "PageSettings")
public class PageSettings {

    @XmlAttribute(name = "BottomMargin")
    protected Integer bottomMargin;
    @XmlAttribute(name = "LeftMargin")
    protected Integer leftMargin;
    @XmlAttribute(name = "Orientation")
    protected PrintOrientationEnum orientation;
    @XmlAttribute(name = "PaperSize")
    protected Integer paperSize;
    @XmlAttribute(name = "PaperSizeString")
    protected java.lang.String paperSizeString;
    @XmlAttribute(name = "Reduction")
    protected Integer reduction;
    @XmlAttribute(name = "RightMargin")
    protected Integer rightMargin;
    @XmlAttribute(name = "TopMargin")
    protected Integer topMargin;
    @XmlAttribute(name = "ThemeNameWidth")
    protected Integer themeNameWidth;

    /**
     * Gets the value of the bottomMargin property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getBottomMargin() {
        return bottomMargin;
    }

    /**
     * Sets the value of the bottomMargin property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBottomMargin(Integer value) {
        this.bottomMargin = value;
    }

    /**
     * Gets the value of the leftMargin property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLeftMargin() {
        return leftMargin;
    }

    /**
     * Sets the value of the leftMargin property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLeftMargin(Integer value) {
        this.leftMargin = value;
    }

    /**
     * Gets the value of the orientation property.
     * 
     * @return
     *     possible object is
     *     {@link PrintOrientationEnum }
     *     
     */
    public PrintOrientationEnum getOrientation() {
        return orientation;
    }

    /**
     * Sets the value of the orientation property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrintOrientationEnum }
     *     
     */
    public void setOrientation(PrintOrientationEnum value) {
        this.orientation = value;
    }

    /**
     * Gets the value of the paperSize property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPaperSize() {
        return paperSize;
    }

    /**
     * Sets the value of the paperSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPaperSize(Integer value) {
        this.paperSize = value;
    }

    /**
     * Gets the value of the paperSizeString property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getPaperSizeString() {
        return paperSizeString;
    }

    /**
     * Sets the value of the paperSizeString property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setPaperSizeString(java.lang.String value) {
        this.paperSizeString = value;
    }

    /**
     * Gets the value of the reduction property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getReduction() {
        return reduction;
    }

    /**
     * Sets the value of the reduction property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setReduction(Integer value) {
        this.reduction = value;
    }

    /**
     * Gets the value of the rightMargin property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRightMargin() {
        return rightMargin;
    }

    /**
     * Sets the value of the rightMargin property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRightMargin(Integer value) {
        this.rightMargin = value;
    }

    /**
     * Gets the value of the topMargin property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTopMargin() {
        return topMargin;
    }

    /**
     * Sets the value of the topMargin property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTopMargin(Integer value) {
        this.topMargin = value;
    }

    /**
     * Gets the value of the themeNameWidth property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getThemeNameWidth() {
        return themeNameWidth;
    }

    /**
     * Sets the value of the themeNameWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setThemeNameWidth(Integer value) {
        this.themeNameWidth = value;
    }

}
