//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.08 at 09:29:27 PM CEST 
//


package edu.anb.core;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PrintBorderEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PrintBorderEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="BorderStyleGridRef"/>
 *     &lt;enumeration value="BorderStyleLine"/>
 *     &lt;enumeration value="BorderStyleNone"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PrintBorderEnum")
@XmlEnum
public enum PrintBorderEnum {


    /**
     * Grid references shown around edge of each page.
     * 
     */
    @XmlEnumValue("BorderStyleGridRef")
    BORDER_STYLE_GRID_REF("BorderStyleGridRef"),

    /**
     * Single line border around each page of chart.
     * 
     */
    @XmlEnumValue("BorderStyleLine")
    BORDER_STYLE_LINE("BorderStyleLine"),

    /**
     * No borders.
     * 
     */
    @XmlEnumValue("BorderStyleNone")
    BORDER_STYLE_NONE("BorderStyleNone");
    private final java.lang.String value;

    PrintBorderEnum(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static PrintBorderEnum fromValue(java.lang.String v) {
        for (PrintBorderEnum c: PrintBorderEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
