//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.08 at 09:29:27 PM CEST 
//


package edu.anb.core;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}HeaderCollection" minOccurs="0"/>
 *         &lt;element ref="{}FooterCollection" minOccurs="0"/>
 *         &lt;element ref="{}PageSettings" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="AssemblePages" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="Border" type="{}PrintBorderEnum" />
 *       &lt;attribute name="CentreChart" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="ColourTimeBarBackground" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="HorzPages" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="NumberPages" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="MaxExtentX" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="MaxExtentY" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="MinExtentX" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="MinExtentY" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="OverlapPages" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="PrintChartBackground" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="PrintThemePane" type="{}PrintOptionsEnum" />
 *       &lt;attribute name="PrintTimeBar" type="{}PrintOptionsEnum" />
 *       &lt;attribute name="VertPages" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "headerCollection",
    "footerCollection",
    "pageSettings"
})
@XmlRootElement(name = "PrintSettings")
public class PrintSettings {

    @XmlElement(name = "HeaderCollection")
    protected HeaderCollection headerCollection;
    @XmlElement(name = "FooterCollection")
    protected FooterCollection footerCollection;
    @XmlElement(name = "PageSettings")
    protected PageSettings pageSettings;
    @XmlAttribute(name = "AssemblePages")
    protected Boolean assemblePages;
    @XmlAttribute(name = "Border")
    protected PrintBorderEnum border;
    @XmlAttribute(name = "CentreChart")
    protected Boolean centreChart;
    @XmlAttribute(name = "ColourTimeBarBackground")
    protected Boolean colourTimeBarBackground;
    @XmlAttribute(name = "HorzPages")
    protected Integer horzPages;
    @XmlAttribute(name = "NumberPages")
    protected Boolean numberPages;
    @XmlAttribute(name = "MaxExtentX")
    protected Integer maxExtentX;
    @XmlAttribute(name = "MaxExtentY")
    protected Integer maxExtentY;
    @XmlAttribute(name = "MinExtentX")
    protected Integer minExtentX;
    @XmlAttribute(name = "MinExtentY")
    protected Integer minExtentY;
    @XmlAttribute(name = "OverlapPages")
    protected Boolean overlapPages;
    @XmlAttribute(name = "PrintChartBackground")
    protected Boolean printChartBackground;
    @XmlAttribute(name = "PrintThemePane")
    protected PrintOptionsEnum printThemePane;
    @XmlAttribute(name = "PrintTimeBar")
    protected PrintOptionsEnum printTimeBar;
    @XmlAttribute(name = "VertPages")
    protected Integer vertPages;

    /**
     * Gets the value of the headerCollection property.
     * 
     * @return
     *     possible object is
     *     {@link HeaderCollection }
     *     
     */
    public HeaderCollection getHeaderCollection() {
        return headerCollection;
    }

    /**
     * Sets the value of the headerCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link HeaderCollection }
     *     
     */
    public void setHeaderCollection(HeaderCollection value) {
        this.headerCollection = value;
    }

    /**
     * Gets the value of the footerCollection property.
     * 
     * @return
     *     possible object is
     *     {@link FooterCollection }
     *     
     */
    public FooterCollection getFooterCollection() {
        return footerCollection;
    }

    /**
     * Sets the value of the footerCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link FooterCollection }
     *     
     */
    public void setFooterCollection(FooterCollection value) {
        this.footerCollection = value;
    }

    /**
     * Gets the value of the pageSettings property.
     * 
     * @return
     *     possible object is
     *     {@link PageSettings }
     *     
     */
    public PageSettings getPageSettings() {
        return pageSettings;
    }

    /**
     * Sets the value of the pageSettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link PageSettings }
     *     
     */
    public void setPageSettings(PageSettings value) {
        this.pageSettings = value;
    }

    /**
     * Gets the value of the assemblePages property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAssemblePages() {
        return assemblePages;
    }

    /**
     * Sets the value of the assemblePages property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAssemblePages(Boolean value) {
        this.assemblePages = value;
    }

    /**
     * Gets the value of the border property.
     * 
     * @return
     *     possible object is
     *     {@link PrintBorderEnum }
     *     
     */
    public PrintBorderEnum getBorder() {
        return border;
    }

    /**
     * Sets the value of the border property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrintBorderEnum }
     *     
     */
    public void setBorder(PrintBorderEnum value) {
        this.border = value;
    }

    /**
     * Gets the value of the centreChart property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCentreChart() {
        return centreChart;
    }

    /**
     * Sets the value of the centreChart property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCentreChart(Boolean value) {
        this.centreChart = value;
    }

    /**
     * Gets the value of the colourTimeBarBackground property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isColourTimeBarBackground() {
        return colourTimeBarBackground;
    }

    /**
     * Sets the value of the colourTimeBarBackground property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setColourTimeBarBackground(Boolean value) {
        this.colourTimeBarBackground = value;
    }

    /**
     * Gets the value of the horzPages property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getHorzPages() {
        return horzPages;
    }

    /**
     * Sets the value of the horzPages property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setHorzPages(Integer value) {
        this.horzPages = value;
    }

    /**
     * Gets the value of the numberPages property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isNumberPages() {
        return numberPages;
    }

    /**
     * Sets the value of the numberPages property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNumberPages(Boolean value) {
        this.numberPages = value;
    }

    /**
     * Gets the value of the maxExtentX property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxExtentX() {
        return maxExtentX;
    }

    /**
     * Sets the value of the maxExtentX property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxExtentX(Integer value) {
        this.maxExtentX = value;
    }

    /**
     * Gets the value of the maxExtentY property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxExtentY() {
        return maxExtentY;
    }

    /**
     * Sets the value of the maxExtentY property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxExtentY(Integer value) {
        this.maxExtentY = value;
    }

    /**
     * Gets the value of the minExtentX property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMinExtentX() {
        return minExtentX;
    }

    /**
     * Sets the value of the minExtentX property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMinExtentX(Integer value) {
        this.minExtentX = value;
    }

    /**
     * Gets the value of the minExtentY property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMinExtentY() {
        return minExtentY;
    }

    /**
     * Sets the value of the minExtentY property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMinExtentY(Integer value) {
        this.minExtentY = value;
    }

    /**
     * Gets the value of the overlapPages property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOverlapPages() {
        return overlapPages;
    }

    /**
     * Sets the value of the overlapPages property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOverlapPages(Boolean value) {
        this.overlapPages = value;
    }

    /**
     * Gets the value of the printChartBackground property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPrintChartBackground() {
        return printChartBackground;
    }

    /**
     * Sets the value of the printChartBackground property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPrintChartBackground(Boolean value) {
        this.printChartBackground = value;
    }

    /**
     * Gets the value of the printThemePane property.
     * 
     * @return
     *     possible object is
     *     {@link PrintOptionsEnum }
     *     
     */
    public PrintOptionsEnum getPrintThemePane() {
        return printThemePane;
    }

    /**
     * Sets the value of the printThemePane property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrintOptionsEnum }
     *     
     */
    public void setPrintThemePane(PrintOptionsEnum value) {
        this.printThemePane = value;
    }

    /**
     * Gets the value of the printTimeBar property.
     * 
     * @return
     *     possible object is
     *     {@link PrintOptionsEnum }
     *     
     */
    public PrintOptionsEnum getPrintTimeBar() {
        return printTimeBar;
    }

    /**
     * Sets the value of the printTimeBar property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrintOptionsEnum }
     *     
     */
    public void setPrintTimeBar(PrintOptionsEnum value) {
        this.printTimeBar = value;
    }

    /**
     * Gets the value of the vertPages property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getVertPages() {
        return vertPages;
    }

    /**
     * Sets the value of the vertPages property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setVertPages(Integer value) {
        this.vertPages = value;
    }

}
