//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.08 at 09:29:27 PM CEST 
//


package edu.anb.core;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for PropertyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PropertyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PropertyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RelatedType" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="tGUID" use="required" type="{http://www.i2group.com/Schemas/2001-12-07/LCXSchema}GUIDREF" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="UnrelatedType" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="tGUID" use="required" type="{http://www.i2group.com/Schemas/2001-12-07/LCXSchema}GUIDREF" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Form" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="fGUID" use="required" type="{http://www.i2group.com/Schemas/2001-12-07/LCXSchema}GUIDREF" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="UnrelatedForm" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="fGUID" use="required" type="{http://www.i2group.com/Schemas/2001-12-07/LCXSchema}GUIDREF" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://www.i2group.com/Schemas/2001-12-07/LCXSchema}Sector" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Documentation" type="{http://www.i2group.com/Schemas/2001-12-07/LCXSchema}DocumentationType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="pGUID" use="required" type="{http://www.i2group.com/Schemas/2001-12-07/LCXSchema}GUID" />
 *       &lt;attribute name="baseProperty" type="{http://www.i2group.com/Schemas/2001-12-07/LCXSchema}GUIDREF" />
 *       &lt;attribute name="abstract" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PropertyType", namespace = "http://www.i2group.com/Schemas/2001-12-07/LCXSchema", propOrder = {
    "propertyName",
    "relatedType",
    "unrelatedType",
    "form",
    "unrelatedForm",
    "sector",
    "documentation"
})
public class PropertyType {

    @XmlElement(name = "PropertyName", required = true)
    protected java.lang.String propertyName;
    @XmlElement(name = "RelatedType")
    protected List<PropertyType.RelatedType> relatedType;
    @XmlElement(name = "UnrelatedType")
    protected List<PropertyType.UnrelatedType> unrelatedType;
    @XmlElement(name = "Form")
    protected List<PropertyType.Form> form;
    @XmlElement(name = "UnrelatedForm")
    protected List<PropertyType.UnrelatedForm> unrelatedForm;
    @XmlElementRef(name = "Sector", namespace = "http://www.i2group.com/Schemas/2001-12-07/LCXSchema", type = JAXBElement.class, required = false)
    protected List<JAXBElement<Object>> sector;
    @XmlElement(name = "Documentation")
    protected DocumentationType documentation;
    @XmlAttribute(name = "pGUID", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected java.lang.String pguid;
    @XmlAttribute(name = "baseProperty")
    @XmlIDREF
    protected Object baseProperty;
    @XmlAttribute(name = "abstract")
    protected Boolean _abstract;

    /**
     * Gets the value of the propertyName property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getPropertyName() {
        return propertyName;
    }

    /**
     * Sets the value of the propertyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setPropertyName(java.lang.String value) {
        this.propertyName = value;
    }

    /**
     * Gets the value of the relatedType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relatedType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelatedType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PropertyType.RelatedType }
     * 
     * 
     */
    public List<PropertyType.RelatedType> getRelatedType() {
        if (relatedType == null) {
            relatedType = new ArrayList<PropertyType.RelatedType>();
        }
        return this.relatedType;
    }

    /**
     * Gets the value of the unrelatedType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the unrelatedType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUnrelatedType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PropertyType.UnrelatedType }
     * 
     * 
     */
    public List<PropertyType.UnrelatedType> getUnrelatedType() {
        if (unrelatedType == null) {
            unrelatedType = new ArrayList<PropertyType.UnrelatedType>();
        }
        return this.unrelatedType;
    }

    /**
     * Gets the value of the form property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the form property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getForm().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PropertyType.Form }
     * 
     * 
     */
    public List<PropertyType.Form> getForm() {
        if (form == null) {
            form = new ArrayList<PropertyType.Form>();
        }
        return this.form;
    }

    /**
     * Gets the value of the unrelatedForm property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the unrelatedForm property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUnrelatedForm().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PropertyType.UnrelatedForm }
     * 
     * 
     */
    public List<PropertyType.UnrelatedForm> getUnrelatedForm() {
        if (unrelatedForm == null) {
            unrelatedForm = new ArrayList<PropertyType.UnrelatedForm>();
        }
        return this.unrelatedForm;
    }

    /**
     * Gets the value of the sector property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sector property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSector().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * 
     */
    public List<JAXBElement<Object>> getSector() {
        if (sector == null) {
            sector = new ArrayList<JAXBElement<Object>>();
        }
        return this.sector;
    }

    /**
     * Gets the value of the documentation property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentationType }
     *     
     */
    public DocumentationType getDocumentation() {
        return documentation;
    }

    /**
     * Sets the value of the documentation property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentationType }
     *     
     */
    public void setDocumentation(DocumentationType value) {
        this.documentation = value;
    }

    /**
     * Gets the value of the pguid property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getPGUID() {
        return pguid;
    }

    /**
     * Sets the value of the pguid property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setPGUID(java.lang.String value) {
        this.pguid = value;
    }

    /**
     * Gets the value of the baseProperty property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getBaseProperty() {
        return baseProperty;
    }

    /**
     * Sets the value of the baseProperty property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setBaseProperty(Object value) {
        this.baseProperty = value;
    }

    /**
     * Gets the value of the abstract property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isAbstract() {
        if (_abstract == null) {
            return false;
        } else {
            return _abstract;
        }
    }

    /**
     * Sets the value of the abstract property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAbstract(Boolean value) {
        this._abstract = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="fGUID" use="required" type="{http://www.i2group.com/Schemas/2001-12-07/LCXSchema}GUIDREF" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Form {

        @XmlAttribute(name = "fGUID", required = true)
        @XmlIDREF
        protected Object fguid;

        /**
         * Gets the value of the fguid property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getFGUID() {
            return fguid;
        }

        /**
         * Sets the value of the fguid property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setFGUID(Object value) {
            this.fguid = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="tGUID" use="required" type="{http://www.i2group.com/Schemas/2001-12-07/LCXSchema}GUIDREF" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class RelatedType {

        @XmlAttribute(name = "tGUID", required = true)
        @XmlIDREF
        protected Object tguid;

        /**
         * Gets the value of the tguid property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getTGUID() {
            return tguid;
        }

        /**
         * Sets the value of the tguid property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setTGUID(Object value) {
            this.tguid = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="fGUID" use="required" type="{http://www.i2group.com/Schemas/2001-12-07/LCXSchema}GUIDREF" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class UnrelatedForm {

        @XmlAttribute(name = "fGUID", required = true)
        @XmlIDREF
        protected Object fguid;

        /**
         * Gets the value of the fguid property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getFGUID() {
            return fguid;
        }

        /**
         * Sets the value of the fguid property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setFGUID(Object value) {
            this.fguid = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="tGUID" use="required" type="{http://www.i2group.com/Schemas/2001-12-07/LCXSchema}GUIDREF" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class UnrelatedType {

        @XmlAttribute(name = "tGUID", required = true)
        @XmlIDREF
        protected Object tguid;

        /**
         * Gets the value of the tguid property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getTGUID() {
            return tguid;
        }

        /**
         * Sets the value of the tguid property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setTGUID(Object value) {
            this.tguid = value;
        }

    }

}
