//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.08 at 09:29:27 PM CEST 
//


package edu.anb.core;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}FieldCollection" minOccurs="0"/>
 *         &lt;element ref="{}CustomPropertyCollection" minOccurs="0"/>
 *         &lt;element ref="{}Origin" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fieldCollection",
    "customPropertyCollection",
    "origin"
})
@XmlRootElement(name = "Summary")
public class Summary {

    @XmlElement(name = "FieldCollection")
    protected FieldCollection fieldCollection;
    @XmlElement(name = "CustomPropertyCollection")
    protected CustomPropertyCollection customPropertyCollection;
    @XmlElement(name = "Origin")
    protected Origin origin;

    /**
     * Gets the value of the fieldCollection property.
     * 
     * @return
     *     possible object is
     *     {@link FieldCollection }
     *     
     */
    public FieldCollection getFieldCollection() {
        return fieldCollection;
    }

    /**
     * Sets the value of the fieldCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link FieldCollection }
     *     
     */
    public void setFieldCollection(FieldCollection value) {
        this.fieldCollection = value;
    }

    /**
     * Gets the value of the customPropertyCollection property.
     * 
     * @return
     *     possible object is
     *     {@link CustomPropertyCollection }
     *     
     */
    public CustomPropertyCollection getCustomPropertyCollection() {
        return customPropertyCollection;
    }

    /**
     * Sets the value of the customPropertyCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomPropertyCollection }
     *     
     */
    public void setCustomPropertyCollection(CustomPropertyCollection value) {
        this.customPropertyCollection = value;
    }

    /**
     * Gets the value of the origin property.
     * 
     * @return
     *     possible object is
     *     {@link Origin }
     *     
     */
    public Origin getOrigin() {
        return origin;
    }

    /**
     * Sets the value of the origin property.
     * 
     * @param value
     *     allowed object is
     *     {@link Origin }
     *     
     */
    public void setOrigin(Origin value) {
        this.origin = value;
    }

}
