//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.08 at 09:29:27 PM CEST 
//


package edu.anb.core;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ThemeWiringOptionEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ThemeWiringOptionEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="GoesToNextEventHeight"/>
 *     &lt;enumeration value="KeepsAtEventHeight"/>
 *     &lt;enumeration value="NoDiversion"/>
 *     &lt;enumeration value="ReturnsToThemeHeight"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ThemeWiringOptionEnum")
@XmlEnum
public enum ThemeWiringOptionEnum {


    /**
     * If used for a event frame connection style, the theme line diverts to this event frame. For any use, the theme line height after this point changes to the height of the next connected event frame, provided that event frame is set to divert the theme line.
     * 
     */
    @XmlEnumValue("GoesToNextEventHeight")
    GOES_TO_NEXT_EVENT_HEIGHT("GoesToNextEventHeight"),

    /**
     * The theme line diverts to this event frame. After this point, the theme line remains at the height of this event frame until the next diverting connection on the theme line is encountered. Only applicable to an event frame connection style.
     * 
     */
    @XmlEnumValue("KeepsAtEventHeight")
    KEEPS_AT_EVENT_HEIGHT("KeepsAtEventHeight"),

    /**
     * The theme line does not divert to this event frame. Only applicable to an event frame connection style.
     * 
     */
    @XmlEnumValue("NoDiversion")
    NO_DIVERSION("NoDiversion"),

    /**
     * If used for a event frame connection style, the theme line diverts to this event frame. For any use, the theme line height after this point changes to the height of the theme line icon.
     * 
     */
    @XmlEnumValue("ReturnsToThemeHeight")
    RETURNS_TO_THEME_HEIGHT("ReturnsToThemeHeight");
    private final java.lang.String value;

    ThemeWiringOptionEnum(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static ThemeWiringOptionEnum fromValue(java.lang.String v) {
        for (ThemeWiringOptionEnum c: ThemeWiringOptionEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
