//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.08 at 09:29:27 PM CEST 
//


package edu.anb.core;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}FrameStyle" minOccurs="0"/>
 *         &lt;element ref="{}IconPicture" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="AfterThemeIconWiring" type="{}ThemeWiringOptionEnum" />
 *       &lt;attribute name="Enlargement" type="{}IconEnlargementEnum" />
 *       &lt;attribute ref="{}EntityTypeReference"/>
 *       &lt;attribute name="GoesToChartEnd" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="GoesToChartStart" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="LeftHandTerminator" type="{}ThemeTerminatorEnum" />
 *       &lt;attribute name="LeftMostWiring" type="{}ThemeWiringOptionEnum" />
 *       &lt;attribute name="LineWidth" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="RightHandTerminator" type="{}ThemeTerminatorEnum" />
 *       &lt;attribute name="Strength" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute ref="{}StrengthReference"/>
 *       &lt;attribute name="Type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="IconShadingColour" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "frameStyle",
    "iconPicture"
})
@XmlRootElement(name = "ThemeStyle")
public class ThemeStyle {

    @XmlElement(name = "FrameStyle")
    protected FrameStyle frameStyle;
    @XmlElement(name = "IconPicture")
    protected IconPicture iconPicture;
    @XmlAttribute(name = "AfterThemeIconWiring")
    protected ThemeWiringOptionEnum afterThemeIconWiring;
    @XmlAttribute(name = "Enlargement")
    protected IconEnlargementEnum enlargement;
    @XmlAttribute(name = "EntityTypeReference")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object entityTypeReference;
    @XmlAttribute(name = "GoesToChartEnd")
    protected Boolean goesToChartEnd;
    @XmlAttribute(name = "GoesToChartStart")
    protected Boolean goesToChartStart;
    @XmlAttribute(name = "LeftHandTerminator")
    protected ThemeTerminatorEnum leftHandTerminator;
    @XmlAttribute(name = "LeftMostWiring")
    protected ThemeWiringOptionEnum leftMostWiring;
    @XmlAttribute(name = "LineWidth")
    protected Integer lineWidth;
    @XmlAttribute(name = "RightHandTerminator")
    protected ThemeTerminatorEnum rightHandTerminator;
    @XmlAttribute(name = "Strength")
    protected java.lang.String strength;
    @XmlAttribute(name = "StrengthReference")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object strengthReference;
    @XmlAttribute(name = "Type")
    protected java.lang.String type;
    @XmlAttribute(name = "IconShadingColour")
    protected Integer iconShadingColour;

    /**
     * Gets the value of the frameStyle property.
     * 
     * @return
     *     possible object is
     *     {@link FrameStyle }
     *     
     */
    public FrameStyle getFrameStyle() {
        return frameStyle;
    }

    /**
     * Sets the value of the frameStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link FrameStyle }
     *     
     */
    public void setFrameStyle(FrameStyle value) {
        this.frameStyle = value;
    }

    /**
     * Picture stored with a chart item.
     * 
     * @return
     *     possible object is
     *     {@link IconPicture }
     *     
     */
    public IconPicture getIconPicture() {
        return iconPicture;
    }

    /**
     * Sets the value of the iconPicture property.
     * 
     * @param value
     *     allowed object is
     *     {@link IconPicture }
     *     
     */
    public void setIconPicture(IconPicture value) {
        this.iconPicture = value;
    }

    /**
     * Gets the value of the afterThemeIconWiring property.
     * 
     * @return
     *     possible object is
     *     {@link ThemeWiringOptionEnum }
     *     
     */
    public ThemeWiringOptionEnum getAfterThemeIconWiring() {
        return afterThemeIconWiring;
    }

    /**
     * Sets the value of the afterThemeIconWiring property.
     * 
     * @param value
     *     allowed object is
     *     {@link ThemeWiringOptionEnum }
     *     
     */
    public void setAfterThemeIconWiring(ThemeWiringOptionEnum value) {
        this.afterThemeIconWiring = value;
    }

    /**
     * Gets the value of the enlargement property.
     * 
     * @return
     *     possible object is
     *     {@link IconEnlargementEnum }
     *     
     */
    public IconEnlargementEnum getEnlargement() {
        return enlargement;
    }

    /**
     * Sets the value of the enlargement property.
     * 
     * @param value
     *     allowed object is
     *     {@link IconEnlargementEnum }
     *     
     */
    public void setEnlargement(IconEnlargementEnum value) {
        this.enlargement = value;
    }

    /**
     * Type IDREF of entity used by this style. An entity type is a category of entity.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getEntityTypeReference() {
        return entityTypeReference;
    }

    /**
     * Sets the value of the entityTypeReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setEntityTypeReference(Object value) {
        this.entityTypeReference = value;
    }

    /**
     * Gets the value of the goesToChartEnd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isGoesToChartEnd() {
        return goesToChartEnd;
    }

    /**
     * Sets the value of the goesToChartEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setGoesToChartEnd(Boolean value) {
        this.goesToChartEnd = value;
    }

    /**
     * Gets the value of the goesToChartStart property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isGoesToChartStart() {
        return goesToChartStart;
    }

    /**
     * Sets the value of the goesToChartStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setGoesToChartStart(Boolean value) {
        this.goesToChartStart = value;
    }

    /**
     * Gets the value of the leftHandTerminator property.
     * 
     * @return
     *     possible object is
     *     {@link ThemeTerminatorEnum }
     *     
     */
    public ThemeTerminatorEnum getLeftHandTerminator() {
        return leftHandTerminator;
    }

    /**
     * Sets the value of the leftHandTerminator property.
     * 
     * @param value
     *     allowed object is
     *     {@link ThemeTerminatorEnum }
     *     
     */
    public void setLeftHandTerminator(ThemeTerminatorEnum value) {
        this.leftHandTerminator = value;
    }

    /**
     * Gets the value of the leftMostWiring property.
     * 
     * @return
     *     possible object is
     *     {@link ThemeWiringOptionEnum }
     *     
     */
    public ThemeWiringOptionEnum getLeftMostWiring() {
        return leftMostWiring;
    }

    /**
     * Sets the value of the leftMostWiring property.
     * 
     * @param value
     *     allowed object is
     *     {@link ThemeWiringOptionEnum }
     *     
     */
    public void setLeftMostWiring(ThemeWiringOptionEnum value) {
        this.leftMostWiring = value;
    }

    /**
     * Gets the value of the lineWidth property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLineWidth() {
        return lineWidth;
    }

    /**
     * Sets the value of the lineWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLineWidth(Integer value) {
        this.lineWidth = value;
    }

    /**
     * Gets the value of the rightHandTerminator property.
     * 
     * @return
     *     possible object is
     *     {@link ThemeTerminatorEnum }
     *     
     */
    public ThemeTerminatorEnum getRightHandTerminator() {
        return rightHandTerminator;
    }

    /**
     * Sets the value of the rightHandTerminator property.
     * 
     * @param value
     *     allowed object is
     *     {@link ThemeTerminatorEnum }
     *     
     */
    public void setRightHandTerminator(ThemeTerminatorEnum value) {
        this.rightHandTerminator = value;
    }

    /**
     * Gets the value of the strength property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getStrength() {
        return strength;
    }

    /**
     * Sets the value of the strength property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setStrength(java.lang.String value) {
        this.strength = value;
    }

    /**
     * Strength IDREF associated with the theme line, which controls the theme line appearance.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getStrengthReference() {
        return strengthReference;
    }

    /**
     * Sets the value of the strengthReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setStrengthReference(Object value) {
        this.strengthReference = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setType(java.lang.String value) {
        this.type = value;
    }

    /**
     * Gets the value of the iconShadingColour property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIconShadingColour() {
        return iconShadingColour;
    }

    /**
     * Sets the value of the iconShadingColour property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIconShadingColour(Integer value) {
        this.iconShadingColour = value;
    }

}
