//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.08 at 09:29:27 PM CEST 
//


package edu.anb.core;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for TypeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TypeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TypeName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ImageFile" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="LNMapping" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="IconFile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="TypeName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="locale" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://www.i2group.com/Schemas/2001-12-07/LCXSchema}Sector" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Documentation" type="{http://www.i2group.com/Schemas/2001-12-07/LCXSchema}DocumentationType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="tGUID" use="required" type="{http://www.i2group.com/Schemas/2001-12-07/LCXSchema}GUID" />
 *       &lt;attribute name="kindOf" type="{http://www.i2group.com/Schemas/2001-12-07/LCXSchema}GUIDREF" />
 *       &lt;attribute name="abstract" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="isSymmetricLink" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TypeType", namespace = "http://www.i2group.com/Schemas/2001-12-07/LCXSchema", propOrder = {
    "typeName",
    "imageFile",
    "lnMapping",
    "sector",
    "documentation"
})
public class TypeType {

    @XmlElement(name = "TypeName", required = true)
    protected java.lang.String typeName;
    @XmlElement(name = "ImageFile")
    protected List<java.lang.String> imageFile;
    @XmlElement(name = "LNMapping")
    protected List<TypeType.LNMapping> lnMapping;
    @XmlElementRef(name = "Sector", namespace = "http://www.i2group.com/Schemas/2001-12-07/LCXSchema", type = JAXBElement.class, required = false)
    protected List<JAXBElement<Object>> sector;
    @XmlElement(name = "Documentation")
    protected DocumentationType documentation;
    @XmlAttribute(name = "tGUID", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected java.lang.String tguid;
    @XmlAttribute(name = "kindOf")
    @XmlIDREF
    protected Object kindOf;
    @XmlAttribute(name = "abstract")
    protected Boolean _abstract;
    @XmlAttribute(name = "isSymmetricLink")
    protected Boolean isSymmetricLink;

    /**
     * Gets the value of the typeName property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getTypeName() {
        return typeName;
    }

    /**
     * Sets the value of the typeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setTypeName(java.lang.String value) {
        this.typeName = value;
    }

    /**
     * Gets the value of the imageFile property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the imageFile property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getImageFile().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link java.lang.String }
     * 
     * 
     */
    public List<java.lang.String> getImageFile() {
        if (imageFile == null) {
            imageFile = new ArrayList<java.lang.String>();
        }
        return this.imageFile;
    }

    /**
     * Gets the value of the lnMapping property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lnMapping property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLNMapping().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TypeType.LNMapping }
     * 
     * 
     */
    public List<TypeType.LNMapping> getLNMapping() {
        if (lnMapping == null) {
            lnMapping = new ArrayList<TypeType.LNMapping>();
        }
        return this.lnMapping;
    }

    /**
     * Gets the value of the sector property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sector property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSector().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * 
     */
    public List<JAXBElement<Object>> getSector() {
        if (sector == null) {
            sector = new ArrayList<JAXBElement<Object>>();
        }
        return this.sector;
    }

    /**
     * Gets the value of the documentation property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentationType }
     *     
     */
    public DocumentationType getDocumentation() {
        return documentation;
    }

    /**
     * Sets the value of the documentation property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentationType }
     *     
     */
    public void setDocumentation(DocumentationType value) {
        this.documentation = value;
    }

    /**
     * Gets the value of the tguid property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getTGUID() {
        return tguid;
    }

    /**
     * Sets the value of the tguid property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setTGUID(java.lang.String value) {
        this.tguid = value;
    }

    /**
     * Gets the value of the kindOf property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getKindOf() {
        return kindOf;
    }

    /**
     * Sets the value of the kindOf property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setKindOf(Object value) {
        this.kindOf = value;
    }

    /**
     * Gets the value of the abstract property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isAbstract() {
        if (_abstract == null) {
            return false;
        } else {
            return _abstract;
        }
    }

    /**
     * Sets the value of the abstract property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAbstract(Boolean value) {
        this._abstract = value;
    }

    /**
     * Gets the value of the isSymmetricLink property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsSymmetricLink() {
        return isSymmetricLink;
    }

    /**
     * Sets the value of the isSymmetricLink property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsSymmetricLink(Boolean value) {
        this.isSymmetricLink = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="IconFile" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="TypeName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *       &lt;attribute name="locale" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "iconFile",
        "typeName"
    })
    public static class LNMapping {

        @XmlElement(name = "IconFile", required = true)
        protected java.lang.String iconFile;
        @XmlElement(name = "TypeName", required = true)
        protected java.lang.String typeName;
        @XmlAttribute(name = "locale")
        protected java.lang.String locale;

        /**
         * Gets the value of the iconFile property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String }
         *     
         */
        public java.lang.String getIconFile() {
            return iconFile;
        }

        /**
         * Sets the value of the iconFile property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String }
         *     
         */
        public void setIconFile(java.lang.String value) {
            this.iconFile = value;
        }

        /**
         * Gets the value of the typeName property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String }
         *     
         */
        public java.lang.String getTypeName() {
            return typeName;
        }

        /**
         * Sets the value of the typeName property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String }
         *     
         */
        public void setTypeName(java.lang.String value) {
            this.typeName = value;
        }

        /**
         * Gets the value of the locale property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String }
         *     
         */
        public java.lang.String getLocale() {
            return locale;
        }

        /**
         * Sets the value of the locale property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String }
         *     
         */
        public void setLocale(java.lang.String value) {
            this.locale = value;
        }

    }

}
